/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles_de_paneles;

import alertas.ErrorAlert;
import alertas.SuccessAlert;
import com.toedter.calendar.JDateChooser;
import esperas.Guardando_general;
import interaccion_bd.consultas_de_gestionar_contrato;
import interaccion_bd.opciones_de_gestionar_contrato;
import java.awt.Event;
import paneles.*;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.lang.reflect.Field;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import static paneles_de_paneles.de_gestionar_contrato_editar.nombre_cliente_contrato_editar;
import static paneles_de_paneles.de_gestionar_contrato_editar.numero_contrato_editar;

/**
 *
 * @author RojeruSan
 */
public class de_gestionar_contrato_añadir extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public de_gestionar_contrato_añadir() {
        initComponents();
        lbl_error_nombre_cliente.setVisible(false);
        lbl_error_numero_contrato.setVisible(false);
        lbl_error_fecha_inicio.setVisible(false);
        lbl.setVisible(false);
        lbl_fecha_expira_contrato.setVisible(false);

      //  detectar cambio en jdateChoser (fecha de inicio en agregar contrato)
        fecha_inicio_contrato.getDateEditor().addPropertyChangeListener(
                new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent e) {
                if ("date".equals(e.getPropertyName())) {
                    System.out.println(e.getPropertyName()
                            + ": " + (Date) e.getNewValue());
                    if(fecha_inicio_contrato.getDate()!=null){
                    lbl_fecha_expira_contrato.setText(toma_fecha(fecha_inicio_contrato).substring(0,6)+String.valueOf(Integer.parseInt(toma_fecha(fecha_inicio_contrato).substring(6))+1));
                    lbl.setVisible(true);
                    lbl_fecha_expira_contrato.setVisible(true);
                    }
                }else{
                    lbl_fecha_expira_contrato.setText("");
                    lbl_error_fecha_inicio.setVisible(false);
                    lbl.setVisible(false);
                    lbl_fecha_expira_contrato.setVisible(false);
                }
            }
        });
        this.add(fecha_inicio_contrato);
        
        deshabilitarPegar();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numero_contrato = new rojeru_san.rsfield.RSTextMaterial();
        lbl_error_numero_contrato = new javax.swing.JLabel();
        nombre_cliente_contrato = new rojeru_san.rsfield.RSTextMaterial();
        lbl_error_nombre_cliente = new javax.swing.JLabel();
        fecha_inicio_contrato = new com.toedter.calendar.JDateChooser();
        lbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        boton_guardar_contrato = new rojeru_san.RSButtonRiple();
        lbl_fecha_expira_contrato = new javax.swing.JLabel();
        lbl_error_fecha_inicio = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        numero_contrato.setForeground(new java.awt.Color(0, 0, 0));
        numero_contrato.setColorMaterial(new java.awt.Color(99, 70, 250));
        numero_contrato.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        numero_contrato.setPlaceholder("Número de contrato...");
        numero_contrato.setSelectionColor(new java.awt.Color(220, 23, 111));
        numero_contrato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numero_contratoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numero_contratoKeyTyped(evt);
            }
        });

        lbl_error_numero_contrato.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_numero_contrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_numero_contrato.setText("¡Debe ingresar número de contrato!");

        nombre_cliente_contrato.setForeground(new java.awt.Color(0, 0, 0));
        nombre_cliente_contrato.setColorMaterial(new java.awt.Color(99, 70, 250));
        nombre_cliente_contrato.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nombre_cliente_contrato.setPlaceholder("Nombre cliente...");
        nombre_cliente_contrato.setSelectionColor(new java.awt.Color(220, 23, 111));
        nombre_cliente_contrato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombre_cliente_contratoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombre_cliente_contratoKeyTyped(evt);
            }
        });

        lbl_error_nombre_cliente.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_nombre_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_nombre_cliente.setText("¡Debe ingresar un nombre de cliente!");

        fecha_inicio_contrato.setDateFormatString("dd/MM/yyyy");
        fecha_inicio_contrato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lbl.setForeground(new java.awt.Color(0, 0, 0));
        lbl.setText("Fecha de vencimiento: ");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_coontrato/contrato2.png"))); // NOI18N

        boton_guardar_contrato.setBackground(new java.awt.Color(38, 86, 186));
        boton_guardar_contrato.setText("Guardar Contrato");
        boton_guardar_contrato.setColorHover(new java.awt.Color(173, 187, 194));
        boton_guardar_contrato.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_guardar_contrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardar_contratoActionPerformed(evt);
            }
        });

        lbl_fecha_expira_contrato.setForeground(new java.awt.Color(0, 0, 0));
        lbl_fecha_expira_contrato.setText("FECHA");

        lbl_error_fecha_inicio.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_fecha_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_fecha_inicio.setText("¡Debe ingresar una fecha de inicio!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numero_contrato, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fecha_inicio_contrato, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl)
                                .addGap(0, 0, 0)
                                .addComponent(lbl_fecha_expira_contrato))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbl_error_nombre_cliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nombre_cliente_contrato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_error_numero_contrato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(boton_guardar_contrato, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_error_fecha_inicio))
                        .addContainerGap(92, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numero_contrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_error_numero_contrato, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nombre_cliente_contrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbl_error_nombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecha_inicio_contrato, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_fecha_expira_contrato, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_error_fecha_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton_guardar_contrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

     private void deshabilitarPegar() {
        InputMap map1 = numero_contrato.getInputMap(numero_contrato.WHEN_FOCUSED);
        map1.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");

        InputMap map2 = nombre_cliente_contrato.getInputMap(nombre_cliente_contrato.WHEN_FOCUSED);
        map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    }
    
    private void numero_contratoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numero_contratoKeyReleased
        // TODO add your handling code here:
        if(numero_contrato.getText().length()>0){
            lbl_error_numero_contrato.setVisible(false);
        }

    }//GEN-LAST:event_numero_contratoKeyReleased

    private void nombre_cliente_contratoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_cliente_contratoKeyTyped
        // TODO add your handling code here:
        char letras = evt.getKeyChar();
        if ((letras < 'a' || letras > 'z') && (letras < 'A' | letras > 'Z')) {
            if ((letras != 'ñ') && (letras != 'Ñ') && (letras != 'á') && (letras != 'Á') && (letras != 'é') && (letras != 'É') && (letras != 'í')
                    && (letras != 'Í') && (letras != 'ó') && (letras != 'Ó') && (letras != 'ú') && (letras != 'Ú') && (letras != ' ')) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_nombre_cliente_contratoKeyTyped

    private void numero_contratoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numero_contratoKeyTyped
        // TODO add your handling code here:
        if(numero_contrato.getText().length()<10){
        char num = evt.getKeyChar();
        if ((num < '0' || num > '9')) {
            evt.consume();
        }
        }else{
             evt.consume();
        }
    }//GEN-LAST:event_numero_contratoKeyTyped

    private void nombre_cliente_contratoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_cliente_contratoKeyReleased
        // TODO add your handling code here:
        if(nombre_cliente_contrato.getText().length()>0){
        lbl_error_nombre_cliente.setVisible(false);
    }
    }//GEN-LAST:event_nombre_cliente_contratoKeyReleased

    private void boton_guardar_contratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardar_contratoActionPerformed
       String sql="select * from contrato where numero_contrato='"+numero_contrato.getText()+"'";
       String mje1="El número de contrato que intenta registrar ya existe";
       String mje2="Por favor introduzca un número distinto de contrato";
        if (nombre_cliente_contrato.getText().isEmpty()||numero_contrato.getText().isEmpty()||fecha_inicio_contrato.getDate()==null) {
            if(numero_contrato.getText().isEmpty()){
                numero_contrato.requestFocus();
                lbl_error_numero_contrato.setVisible(true);
            }else if(nombre_cliente_contrato.getText().isEmpty()){
                nombre_cliente_contrato.requestFocus();
                lbl_error_nombre_cliente.setVisible(true);
            }else if(fecha_inicio_contrato.getDate()==null){
                fecha_inicio_contrato.requestFocus();
                lbl_error_fecha_inicio.setVisible(true);
            }
        } else {
            Runnable runnable1 = new Runnable() {
                public void run() {
                    Guardando_general l = new Guardando_general(new JFrame(), true);
                    consultas_de_gestionar_contrato uc=new consultas_de_gestionar_contrato();
                    l.setLocationRelativeTo(paneles_de_paneles.de_gestionar_contrato_añadir.this);
                    l.setVisible(true);
                    try{
                        if (interaccion_bd.opciones_de_gestionar_contrato.existe(numero_contrato.getText(), sql)) {
                            opciones_de_gestionar_contrato.lanza_error_variable_sin_ex("",mje1,mje2);
                            numero_contrato.requestFocus();
                        }else{
                    paneles_de_paneles.de_gestionar_contrato_añadir.this.setEnabled(false);
                    uc.setNumero_contrato(numero_contrato.getText());
                    uc.setNombre_contrato(nombre_cliente_contrato.getText());
                    uc.setFecha_inicio_contrato(toma_fecha(fecha_inicio_contrato));
                    uc.setFecha_final_contrato(lbl_fecha_expira_contrato.getText());
                   int control= opciones_de_gestionar_contrato.registrar(uc);
                    reset_campos();
                    paneles_de_paneles.de_gestionar_contrato_añadir.this.setEnabled(true);
                    l.setVisible(false);
                    if(control==1){
                    SuccessAlert e = new SuccessAlert(new JFrame(), true);
            e.msj1.setText("¡Los datos del contrato fueron");
            e.msj2.setText("guardados exitosamente!.");
            e.msj3.setText("");
            e.setVisible(true);
                    }
                    }
                    }catch(Exception e){
                        ErrorAlert error = new ErrorAlert(new JFrame(), true);
                        Logger.getLogger(opciones_de_gestionar_contrato.class.getName()).log(Level.SEVERE, null, e);
            error.msj1.setText(e.toString());
            error.msj2.setText("Por favor solucione el error antes de volver a intentarlo.");
            error.msj3.setText("En caso de no saber como corregir el error, por favor contacte con soporte técnico");
            error.preferredSize();
            error.pack();
            error.setVisible(true);
                    }
                }
            };
            Thread t1 = new Thread(runnable1);
            t1.start();
        }

    }//GEN-LAST:event_boton_guardar_contratoActionPerformed

    private String toma_fecha(JDateChooser fecha) {      
        String txt_fecha = null;
        if (fecha.getDate() != null) {
             String formato = fecha.getDateFormatString();
            Date date = fecha.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat(formato);
            txt_fecha=String.valueOf(sdf.format(date));
        }
        return txt_fecha;
    }                   
    
    private void reset_campos(){
        numero_contrato.setText("");
        nombre_cliente_contrato.setText("");
        fecha_inicio_contrato.setDate(null);
        lbl.setVisible(false);
        lbl_fecha_expira_contrato.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple boton_guardar_contrato;
    private com.toedter.calendar.JDateChooser fecha_inicio_contrato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl_error_fecha_inicio;
    private javax.swing.JLabel lbl_error_nombre_cliente;
    private javax.swing.JLabel lbl_error_numero_contrato;
    private javax.swing.JLabel lbl_fecha_expira_contrato;
    public static rojeru_san.rsfield.RSTextMaterial nombre_cliente_contrato;
    public static rojeru_san.rsfield.RSTextMaterial numero_contrato;
    // End of variables declaration//GEN-END:variables
}
