/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles_de_paneles;

import alertas.ErrorAlert;
import alertas.SuccessAlert;
import com.toedter.calendar.JDateChooser;
import esperas.Guardando_general;
import interaccion_bd.consultas_de_gestionar_ekipo;
import interaccion_bd.opciones_de_gestionar_contrato;
import interaccion_bd.opciones_de_gestionar_ekipo;
import java.awt.Event;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.InputMap;
import javax.swing.JFrame;
import javax.swing.KeyStroke;

/**
 *
 * @author RojeruSan
 */
public class de_gestionar_ekipo_añadir extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public de_gestionar_ekipo_añadir() {
        initComponents();
        lbl_error_indice_consumo_ekipo.setVisible(false);
        lbl_error_tipo_auto_ekipo.setVisible(false);
        lbl_error_chapa_ekipo.setVisible(false);
        
         //################### detectar cambios en los combobox ######################3
        combo_auto_ekipo.addItemListener(new ItemListener() {
           public void itemStateChanged(ItemEvent arg0) {
               //Do Something
              lbl_error_tipo_auto_ekipo.setVisible(false);
           }
           
            public void itemStateChangedd(ItemEvent e) {
             //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
       });
        // ##########################################################################
        
        
        deshabilitarPegar();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_error_chapa_ekipo = new javax.swing.JLabel();
        numero_chapa_ekipo = new rojeru_san.rsfield.RSTextMaterial();
        indice_consumo_ekipo = new rojeru_san.rsfield.RSTextMaterial();
        lbl_error_indice_consumo_ekipo = new javax.swing.JLabel();
        combo_auto_ekipo = new org.bolivia.combo.SComboBox();
        lbl_error_tipo_auto_ekipo = new javax.swing.JLabel();
        boton_guardar_ekipo = new rojeru_san.RSButtonRiple();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_ekipo/gestionar_ekipo.jpg"))); // NOI18N

        lbl_error_chapa_ekipo.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_chapa_ekipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_chapa_ekipo.setText("¡Debe ingresar número de chapa!");

        numero_chapa_ekipo.setForeground(new java.awt.Color(0, 0, 0));
        numero_chapa_ekipo.setColorMaterial(new java.awt.Color(99, 70, 250));
        numero_chapa_ekipo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        numero_chapa_ekipo.setPlaceholder("Chapa del equipo...");
        numero_chapa_ekipo.setSelectionColor(new java.awt.Color(220, 23, 111));
        numero_chapa_ekipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_chapa_ekipoActionPerformed(evt);
            }
        });
        numero_chapa_ekipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numero_chapa_ekipoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numero_chapa_ekipoKeyTyped(evt);
            }
        });

        indice_consumo_ekipo.setForeground(new java.awt.Color(0, 0, 0));
        indice_consumo_ekipo.setColorMaterial(new java.awt.Color(99, 70, 250));
        indice_consumo_ekipo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        indice_consumo_ekipo.setPlaceholder("Índice de consumo...");
        indice_consumo_ekipo.setSelectionColor(new java.awt.Color(220, 23, 111));
        indice_consumo_ekipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                indice_consumo_ekipoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                indice_consumo_ekipoKeyTyped(evt);
            }
        });

        lbl_error_indice_consumo_ekipo.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_indice_consumo_ekipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_indice_consumo_ekipo.setText("¡Debe ingresar un índice de consumo!");

        combo_auto_ekipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TIPO DE AUTO", "LIGERO", "CARGA" }));
        combo_auto_ekipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_auto_ekipoActionPerformed(evt);
            }
        });

        lbl_error_tipo_auto_ekipo.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_tipo_auto_ekipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_tipo_auto_ekipo.setText("¡Debe ingresar un tipo de auto!");

        boton_guardar_ekipo.setBackground(new java.awt.Color(38, 86, 186));
        boton_guardar_ekipo.setText("Guardar Equipo");
        boton_guardar_ekipo.setColorHover(new java.awt.Color(173, 187, 194));
        boton_guardar_ekipo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_guardar_ekipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardar_ekipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(combo_auto_ekipo, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_error_tipo_auto_ekipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(boton_guardar_ekipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_error_indice_consumo_ekipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(indice_consumo_ekipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lbl_error_chapa_ekipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numero_chapa_ekipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numero_chapa_ekipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbl_error_chapa_ekipo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(indice_consumo_ekipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbl_error_indice_consumo_ekipo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_auto_ekipo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_guardar_ekipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(lbl_error_tipo_auto_ekipo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

     private void deshabilitarPegar() {

        InputMap map1 = indice_consumo_ekipo.getInputMap(indice_consumo_ekipo.WHEN_FOCUSED);
        map1.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
        InputMap map2= numero_chapa_ekipo.getInputMap(numero_chapa_ekipo.WHEN_FOCUSED);
        map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    }
     
    int pto=0;
    int lugares=0;
    int control=0;
    private void indice_consumo_ekipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_indice_consumo_ekipoKeyTyped
        // TODO add your handling code here: 
        char caracter = evt.getKeyChar();
        if(caracter=='.'){
            pto++;
        }
         if( pto>=2){
            pto=2;
           }
        if( lugares>=3){
            lugares--;
           }
        
        if(caracter == KeyEvent.VK_BACK_SPACE){
          if( pto>=0){
            lugares--;
           }
          
          if(!indice_consumo_ekipo.getText().contains(".")){
              pto=0;
          }
          if( pto==0){
            lugares=0;
           }
        }
        if (indice_consumo_ekipo.getText().length() <1 ) {
            char car = evt.getKeyChar();
            if (car!='.' && Character.isDigit(car)) {
                // escribe
            } else {
                evt.consume();  // desecha
            }

        }else{
            if(indice_consumo_ekipo.getText().length()<10){     
        char num = evt.getKeyChar();
        if (Character.isDigit(num)||num=='.') {
            if(num=='.'&&pto<2){
                   // escribe
                }else{
                if(pto!=0&&num!='.'){
                lugares++;
                }
                if(lugares<3 && num!='.'){
                    // escribe
                }else{
                    evt.consume();
                }
                }
        }else{
            evt.consume();
        }
        }else{
            evt.consume();
        }
        }
        
    }//GEN-LAST:event_indice_consumo_ekipoKeyTyped

    private void indice_consumo_ekipoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_indice_consumo_ekipoKeyReleased
        // TODO add your handling code here:
        if(indice_consumo_ekipo.getText().length()>0){
        lbl_error_indice_consumo_ekipo.setVisible(false);
    }
    }//GEN-LAST:event_indice_consumo_ekipoKeyReleased

    private void boton_guardar_ekipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardar_ekipoActionPerformed
      String sql="SELECT * FROM `ekipos` WHERE `chapa_ekipo`='"+numero_chapa_ekipo.getText()+"'";
      String mje1="El auto que intenta introducir al sistema ya existe";
      String mje2="Por favor introduzca uno nuevo";
        if (combo_auto_ekipo.getSelectedIndex()==0||numero_chapa_ekipo.getText().isEmpty()||indice_consumo_ekipo.getText().isEmpty()) {
             if(numero_chapa_ekipo.getText().isEmpty()){
                numero_chapa_ekipo.requestFocus();
                lbl_error_chapa_ekipo.setText("¡Debe ingresar número de chapa!");
                lbl_error_chapa_ekipo.setVisible(true);
            }else if(indice_consumo_ekipo.getText().isEmpty()){
                indice_consumo_ekipo.requestFocus();
                lbl_error_indice_consumo_ekipo.setVisible(true);
            }else if(combo_auto_ekipo.getSelectedIndex()==0){
                combo_auto_ekipo.requestFocus();
                lbl_error_tipo_auto_ekipo.setVisible(true);
            }else if (interaccion_bd.opciones_de_gestionar_contrato.existe(numero_chapa_ekipo.getText(), sql)) {
                            opciones_de_gestionar_contrato.lanza_error_variable_sin_ex(mje1,mje2,"");
                            numero_chapa_ekipo.requestFocus();
                        }else if(numero_chapa_ekipo.getText().length()<7){
                numero_chapa_ekipo.requestFocus();
                lbl_error_chapa_ekipo.setText("¡El campo debe contener 1 letra y 6 dígitos!");
                lbl_error_chapa_ekipo.setVisible(true);
            }
        } else {
            Runnable runnable1 = new Runnable() {
                public void run() {
                    Guardando_general l = new Guardando_general(new JFrame(), true);
                    consultas_de_gestionar_ekipo uc=new consultas_de_gestionar_ekipo();
                    l.setLocationRelativeTo(paneles_de_paneles.de_gestionar_ekipo_añadir.this);
                    l.setVisible(true);
                    try{            //toma_fecha()
                    paneles_de_paneles.de_gestionar_ekipo_añadir.this.setEnabled(false);
                    uc.setNumero_chapa(numero_chapa_ekipo.getText());
                    uc.setTipo_auto(combo_auto_ekipo.getSelectedItem().toString());
                    uc.setIndice_consumo(indice_consumo_ekipo.getText());
                   int control= opciones_de_gestionar_ekipo.registrar(uc);
                    reset_campos();
                    paneles_de_paneles.de_gestionar_ekipo_añadir.this.setEnabled(true);
                    l.setVisible(false);
                    if(control==1){
                    SuccessAlert e = new SuccessAlert(new JFrame(), true);
            e.msj1.setText("¡Los datos del contrato fueron");
            e.msj2.setText("guardados exitosamente!.");
            e.msj3.setText("");
            e.setVisible(true);
                    }
                    
                    }catch(Exception e){
                        ErrorAlert error = new ErrorAlert(new JFrame(), true);
                        Logger.getLogger(opciones_de_gestionar_contrato.class.getName()).log(Level.SEVERE, null, e);
            error.msj1.setText(e.toString());
            error.msj2.setText("Por favor solucione el error antes de volver a intentarlo.");
            error.msj3.setText("En caso de no saber como corregir el error, por favor contacte con soporte técnico");
            error.preferredSize();
            error.pack();
            error.setVisible(true);
                    }
                }
            };
            Thread t1 = new Thread(runnable1);
            t1.start();
        }

    }//GEN-LAST:event_boton_guardar_ekipoActionPerformed

    private void numero_chapa_ekipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_chapa_ekipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero_chapa_ekipoActionPerformed

    private void numero_chapa_ekipoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numero_chapa_ekipoKeyReleased
        // TODO add your handling code here:
        
        if(numero_chapa_ekipo.getText().length()>0){
            lbl_error_chapa_ekipo.setVisible(false);
            char car = numero_chapa_ekipo.getText().charAt(0);
            car=Character.toUpperCase(car);
            String txt=numero_chapa_ekipo.getText().substring(1);
            numero_chapa_ekipo.setText(String.valueOf(car)+txt);
        }
    }//GEN-LAST:event_numero_chapa_ekipoKeyReleased

    private void numero_chapa_ekipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numero_chapa_ekipoKeyTyped
        // TODO add your handling code here:
            
        if (numero_chapa_ekipo.getText().length() > 0 &&numero_chapa_ekipo.getText().length() < 7) {
            char car = evt.getKeyChar();
            if (Character.isDigit(car)) {
                
            } else {
                evt.consume();
            }

        }else{
            if(numero_chapa_ekipo.getText().length() < 7){
        char car = evt.getKeyChar();
        if ( Character.isLetter(car)) {
            
        } else {
            evt.consume();
        }
        }else{
                evt.consume();
            }
        }
    }//GEN-LAST:event_numero_chapa_ekipoKeyTyped

    private void combo_auto_ekipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_auto_ekipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_auto_ekipoActionPerformed

    private String toma_fecha(JDateChooser fecha) {      
        String txt_fecha = null;
        if (fecha.getDate() != null) {
             String formato = fecha.getDateFormatString();
            Date date = fecha.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat(formato);
            txt_fecha=String.valueOf(sdf.format(date));
        }
        return txt_fecha;
    }                   
    
    private void reset_campos(){
        indice_consumo_ekipo.setText("");
        numero_chapa_ekipo.setText("");
        combo_auto_ekipo.setSelectedIndex(0);
        lbl_error_indice_consumo_ekipo.setVisible(false);
        lbl_error_tipo_auto_ekipo.setVisible(false);
        lbl_error_chapa_ekipo.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple boton_guardar_ekipo;
    private org.bolivia.combo.SComboBox combo_auto_ekipo;
    public static rojeru_san.rsfield.RSTextMaterial indice_consumo_ekipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_error_chapa_ekipo;
    private javax.swing.JLabel lbl_error_indice_consumo_ekipo;
    private javax.swing.JLabel lbl_error_tipo_auto_ekipo;
    public static rojeru_san.rsfield.RSTextMaterial numero_chapa_ekipo;
    // End of variables declaration//GEN-END:variables
}
