/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles_de_paneles;

import DAO.PdfDAO;
import DAO.PdfDAO_hoja_ruta;
import Tabla.Tabla_PdfVO;
import Tabla.Tabla_PdfVO_hoja_ruta;
import VO.PdfVO;
import VO.PdfVO_hoja_ruta;
import alertas.ErrorAlert;
import alertas.SuccessAlert;
import alertas.WarningAlert;
import esperas.Guardando_general;
import interaccion_bd.opciones_de_gestionar_contrato;
import interaccion_bd.opciones_de_gestionar_hoja_ruta;
import interaccion_bd.opciones_de_gestionar_prod_programa;
import java.awt.Event;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.InputMap;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import static paneles_de_paneles.de_gestionar_contrato_añadir.numero_contrato;

/**
 *
 * @author RojeruSan
 */
public class de_gestionar_hoja_ruta_añadir extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public de_gestionar_hoja_ruta_añadir() {
        initComponents();
        lbl_error_chapa_hoja_ruta.setVisible(false);
        lbl_error_km_hoja_ruta.setVisible(false);
        lbl_error_pdf_hoja_ruta.setVisible(false);
        deshabilitarPegar();
        opciones_de_gestionar_hoja_ruta.get_combos(combo_chapa_hoja_ruta);
        //###################### detectar cambio en combobox ####################
        combo_chapa_hoja_ruta.addItemListener(new ItemListener() {
           public void itemStateChanged(ItemEvent arg0) {
               //Do Something
              lbl_error_chapa_hoja_ruta.setVisible(false);
           }
           
            public void itemStateChangedd(ItemEvent e) {
             //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
       });
      //###########################################################################  
    }

     String  ruta_archivo="";
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_error_chapa_hoja_ruta = new javax.swing.JLabel();
        boton_guardar__hoja_ruta = new rojeru_san.RSButtonRiple();
        lb_foto = new javax.swing.JLabel();
        boton_busca__hoja_ruta = new rojeru_san.RSButtonRiple();
        lbl_error_pdf_hoja_ruta = new javax.swing.JLabel();
        km_hoja_ruta = new rojeru_san.rsfield.RSTextMaterial();
        lbl_error_km_hoja_ruta = new javax.swing.JLabel();
        combo_chapa_hoja_ruta = new org.bolivia.combo.SComboBox();
        check_android_hoja_ruta = new check_de_android.Switch();

        setBackground(new java.awt.Color(255, 255, 255));

        lbl_error_chapa_hoja_ruta.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_chapa_hoja_ruta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_chapa_hoja_ruta.setText("¡Debe ingresar una chapa de vehiculo!");

        boton_guardar__hoja_ruta.setBackground(new java.awt.Color(38, 86, 186));
        boton_guardar__hoja_ruta.setText("Guardar Hoja de Ruta");
        boton_guardar__hoja_ruta.setColorHover(new java.awt.Color(173, 187, 194));
        boton_guardar__hoja_ruta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_guardar__hoja_ruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardar__hoja_rutaActionPerformed(evt);
            }
        });

        lb_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_hoja_ruta/prueba fibnal.png"))); // NOI18N

        boton_busca__hoja_ruta.setBackground(new java.awt.Color(38, 86, 186));
        boton_busca__hoja_ruta.setText("Buscar Hoja de Ruta");
        boton_busca__hoja_ruta.setColorHover(new java.awt.Color(173, 187, 194));
        boton_busca__hoja_ruta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_busca__hoja_ruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_busca__hoja_rutaActionPerformed(evt);
            }
        });

        lbl_error_pdf_hoja_ruta.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_pdf_hoja_ruta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_pdf_hoja_ruta.setText("¡Debe buscar una hoja de ruta!");

        km_hoja_ruta.setForeground(new java.awt.Color(0, 0, 0));
        km_hoja_ruta.setColorMaterial(new java.awt.Color(99, 70, 250));
        km_hoja_ruta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        km_hoja_ruta.setPlaceholder("Total de km recorridos...");
        km_hoja_ruta.setSelectionColor(new java.awt.Color(220, 23, 111));
        km_hoja_ruta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                km_hoja_rutaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                km_hoja_rutaKeyTyped(evt);
            }
        });

        lbl_error_km_hoja_ruta.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_km_hoja_ruta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_km_hoja_ruta.setText("¡Debe ingresar un total de km!");

        combo_chapa_hoja_ruta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CHAPA DEL VEHÍCULO" }));
        combo_chapa_hoja_ruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_chapa_hoja_rutaActionPerformed(evt);
            }
        });

        check_android_hoja_ruta.setOnOff(false);
        check_android_hoja_ruta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check_android_hoja_rutaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_error_pdf_hoja_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_busca__hoja_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(boton_guardar__hoja_ruta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_error_chapa_hoja_ruta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(km_hoja_ruta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_error_km_hoja_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(combo_chapa_hoja_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(check_android_hoja_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_foto)
                        .addGap(29, 29, 29)
                        .addComponent(boton_busca__hoja_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_chapa_hoja_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(check_android_hoja_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(lbl_error_chapa_hoja_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(km_hoja_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbl_error_km_hoja_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(boton_guardar__hoja_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(lbl_error_pdf_hoja_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    Tabla_PdfVO_hoja_ruta tpdf = new Tabla_PdfVO_hoja_ruta();
    private void boton_guardar__hoja_rutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardar__hoja_rutaActionPerformed
      
        if (combo_chapa_hoja_ruta.getSelectedIndex()==0||boton_busca__hoja_ruta.getText().equals("Buscar Hoja de Ruta")||km_hoja_ruta.getText().isEmpty()) {
               if(combo_chapa_hoja_ruta.getSelectedIndex()==0){
                lbl_error_chapa_hoja_ruta.setVisible(true);
               }else if(km_hoja_ruta.getText().isEmpty()){
                   lbl_error_km_hoja_ruta.setVisible(true);
               }else if(boton_busca__hoja_ruta.getText().equals("Buscar Hoja de Ruta")){
                lbl_error_pdf_hoja_ruta.setVisible(true);
               }
        } else {
            Runnable runnable1 = new Runnable() {
                public void run() {
                    Guardando_general l = new Guardando_general(new JFrame(), true);
                    l.setLocationRelativeTo(paneles_de_paneles.de_gestionar_hoja_ruta_añadir.this);
                    l.setVisible(true);
                    try{
                    paneles_de_paneles.de_gestionar_hoja_ruta_añadir.this.setEnabled(false);
                    accion_guardar();
                    paneles_de_paneles.de_gestionar_hoja_ruta_añadir.this.setEnabled(true);
                    l.setVisible(false);
                        
                    }catch(Exception e){
                        ErrorAlert error = new ErrorAlert(new JFrame(), true);
                        Logger.getLogger(opciones_de_gestionar_contrato.class.getName()).log(Level.SEVERE, null, e);
            error.msj1.setText(e.toString());
            error.msj2.setText("Por favor solucione el error antes de volver a intentarlo.");
            error.msj3.setText("En caso de no saber como corregir el error, por favor contacte con soporte técnico");
            error.preferredSize();
            error.pack();
            error.setVisible(true);
                    }
                }
            };
            Thread t1 = new Thread(runnable1);
            t1.start();
        
    }
    }//GEN-LAST:event_boton_guardar__hoja_rutaActionPerformed

    private double dame_consumo(String chapa){
        double consumo=0;
        String sql_indice_consumo="SELECT `indice_consumo_ekipo` FROM `ekipos` WHERE `chapa_ekipo`='"+chapa+"'";
        consumo=opciones_de_gestionar_hoja_ruta.extraer_indice_consumo(sql_indice_consumo);
        return consumo;
    }
    
    public void accion_guardar(){
        try{
        String chapa = combo_chapa_hoja_ruta.getSelectedItem().toString();
        String km = km_hoja_ruta.getText();
        String consumo = String.valueOf(dame_consumo(chapa)*Double.parseDouble(km));
        File ruta = new File(ruta_archivo);
        if (chapa.trim().length() != 0 && ruta_archivo.trim().length() != 0) {
            guardar_pdf(chapa, km, consumo, ruta);
         //   tpdf.visualizar_PdfVO(tabla);
            ruta_archivo = "";
            reset_campos();
            SuccessAlert e = new SuccessAlert(new JFrame(), true);
            e.msj1.setText("¡Los datos de la hoja de ruta fueron");
            e.msj2.setText("guardados exitosamente!.");
            e.msj3.setText("");
            e.setVisible(true);
        } 
        }catch(Exception ex){
            opciones_de_gestionar_contrato.lanza_error(ex);
        }
    }
    
    public void guardar_pdf( String chapa, String km, String consumo, File ruta) {
        PdfDAO_hoja_ruta pa = new PdfDAO_hoja_ruta();
        PdfVO_hoja_ruta po = new PdfVO_hoja_ruta();
        po.setChapa(chapa);
        po.setTotal_km(km);
        po.setConsumo(consumo);
        try {
            byte[] pdf = new byte[(int) ruta.length()];
            InputStream input = new FileInputStream(ruta);
            input.read(pdf);
            po.setArchivopdf(pdf);
        } catch (IOException ex) {
            po.setArchivopdf(null);
        }
        pa.Agregar_PdfVO(po);
    }
    
    private void boton_busca__hoja_rutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_busca__hoja_rutaActionPerformed
        // TODO add your handling code here:
        try{
         JFileChooser j = new JFileChooser();
        FileNameExtensionFilter fi = new FileNameExtensionFilter("pdf", "pdf");
        j.setFileFilter(fi);
        int se = j.showOpenDialog(this);
        if (se == 0) {
            this.boton_busca__hoja_ruta.setText("" + j.getSelectedFile().getName());
          ruta_archivo = j.getSelectedFile().getAbsolutePath();
          
          lb_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_planos/pdf2.png"))); 
          lbl_error_pdf_hoja_ruta.setVisible(false);
        }  
        }catch(Exception ex){
            opciones_de_gestionar_contrato.lanza_error(ex);
        }
    }//GEN-LAST:event_boton_busca__hoja_rutaActionPerformed

    private void km_hoja_rutaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_km_hoja_rutaKeyReleased
        // TODO add your handling code here:
        if(km_hoja_ruta.getText().length()>0){
            lbl_error_km_hoja_ruta.setVisible(false);
        }
    }//GEN-LAST:event_km_hoja_rutaKeyReleased

    
    int pto=0;
    int lugares=0;
    private void km_hoja_rutaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_km_hoja_rutaKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if(caracter=='.'){
            pto++;
        }
         if( pto>=2){
            pto=2;
           }
        if( lugares>=3){
            lugares--;
           }
        
        if(caracter == KeyEvent.VK_BACK_SPACE){
          if( pto>=0){
            lugares--;
           }
          
          if(!km_hoja_ruta.getText().contains(".")){
              pto=0;
          }
          if( pto==0){
            lugares=0;
           }
        }
        if (km_hoja_ruta.getText().length() <1 ) {
            char car = evt.getKeyChar();
            if (car!='.' && Character.isDigit(car)) {
                // escribe
            } else {
                evt.consume();  // desecha
            }

        }else{
            if(km_hoja_ruta.getText().length()<10){     
        char num = evt.getKeyChar();
        if (Character.isDigit(num)||num=='.') {
            if(num=='.'&&pto<2){
                   // escribe
                }else{
                if(pto!=0&&num!='.'){
                lugares++;
                }
                if(lugares<3 && num!='.'){
                    // escribe
                }else{
                    evt.consume();
                }
                }
        }else{
            evt.consume();
        }
        }else{
            evt.consume();
        }
        }
    }//GEN-LAST:event_km_hoja_rutaKeyTyped

    private void combo_chapa_hoja_rutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_chapa_hoja_rutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_chapa_hoja_rutaActionPerformed

    private void check_android_hoja_rutaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check_android_hoja_rutaMouseClicked
        // TODO add your handling code here:
        if(check_android_hoja_ruta.isOnOff()){
            combo_chapa_hoja_ruta.setEditable(true);
        AutoCompleteDecorator.decorate(combo_chapa_hoja_ruta);
        }else{
            combo_chapa_hoja_ruta.setEditable(false);
            combo_chapa_hoja_ruta.requestFocus();
        }
    }//GEN-LAST:event_check_android_hoja_rutaMouseClicked

     private void deshabilitarPegar() {
        
        
         InputMap map1 = km_hoja_ruta.getInputMap(km_hoja_ruta.WHEN_FOCUSED);
        map1.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    }
               
    private void reset_campos(){
        combo_chapa_hoja_ruta.setSelectedIndex(0);
        km_hoja_ruta.setText("");
        boton_busca__hoja_ruta.setText("Buscar Hoja de Ruta");
        lb_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_hoja_ruta/prueba fibnal.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple boton_busca__hoja_ruta;
    private rojeru_san.RSButtonRiple boton_guardar__hoja_ruta;
    private check_de_android.Switch check_android_hoja_ruta;
    public static org.bolivia.combo.SComboBox combo_chapa_hoja_ruta;
    public static rojeru_san.rsfield.RSTextMaterial km_hoja_ruta;
    private javax.swing.JLabel lb_foto;
    private javax.swing.JLabel lbl_error_chapa_hoja_ruta;
    private javax.swing.JLabel lbl_error_km_hoja_ruta;
    private javax.swing.JLabel lbl_error_pdf_hoja_ruta;
    // End of variables declaration//GEN-END:variables
}
