/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles_de_paneles;

import DAO.PdfDAO;
import DAO.PdfDAO_cartaporte;
import Tabla.Tabla_PdfVO;
import Tabla.Tabla_PdfVO_cartaporte;
import VO.PdfVO;
import VO.PdfVO_cartaporte;
import alertas.*;
import com.toedter.calendar.JDateChooser;
import esperas.Guardando_general;
import interaccion_bd.opciones_de_gestionar_contrato;
import java.awt.Event;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.text.ParseException; 
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import javax.swing.filechooser.FileNameExtensionFilter;
import necesario.RSAWTUtilities;
import static paneles_de_paneles.de_gestionar_plano_listar.tabla_plano;
import rojeru_san.complementos.RSMoveObject;
import rojeru_san.complementos.RSUtilities;

/**
 *
 * @author RojeruSan
 */
public class de_gestionar_cartaporte_editar extends javax.swing.JDialog {

    /**
     * Creates new form ErrorAlert
     */
    public de_gestionar_cartaporte_editar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
lbl_error_numero_cartaporte_editar.setVisible(false);
        lbl_error_pdf_cartaporte_editar.setVisible(false);
        id_cartaporte.setVisible(false);
        numero_cartaporte_control.setVisible(false);
        deshabilitarPegar();
        RSAWTUtilities.setOpaque(this, false);
        RSUtilities.setCentrarVentana(this);
        RSMoveObject.setMoverVentana(this);
        addEventKey();
    }
     String  ruta_archivo="";
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelShadow1 = new rojeru_san.rspanel.RSPanelShadow();
        jPanel1 = new javax.swing.JPanel();
        lb_foto = new javax.swing.JLabel();
        boton_busca_cartaporte_editar = new rojeru_san.RSButtonRiple();
        lbl_error_pdf_cartaporte_editar = new javax.swing.JLabel();
        boton_guardar_cartaporte_editar = new rojeru_san.RSButtonRiple();
        lbl_error_numero_cartaporte_editar = new javax.swing.JLabel();
        numero_cartaporte_editar = new rojeru_san.rsfield.RSTextMaterial();
        id_cartaporte = new javax.swing.JLabel();
        numero_cartaporte_control = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        rSPanelShadow1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(782, 552));

        lb_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_carta_porte/cartaporte.png"))); // NOI18N

        boton_busca_cartaporte_editar.setBackground(new java.awt.Color(38, 86, 186));
        boton_busca_cartaporte_editar.setText("Modificar Carta de Porte");
        boton_busca_cartaporte_editar.setColorHover(new java.awt.Color(173, 187, 194));
        boton_busca_cartaporte_editar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_busca_cartaporte_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_busca_cartaporte_editarActionPerformed(evt);
            }
        });

        lbl_error_pdf_cartaporte_editar.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_pdf_cartaporte_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_pdf_cartaporte_editar.setText("¡Debe buscar una carta de porte!");

        boton_guardar_cartaporte_editar.setBackground(new java.awt.Color(38, 86, 186));
        boton_guardar_cartaporte_editar.setText("Guardar Cambios");
        boton_guardar_cartaporte_editar.setColorHover(new java.awt.Color(173, 187, 194));
        boton_guardar_cartaporte_editar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_guardar_cartaporte_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardar_cartaporte_editarActionPerformed(evt);
            }
        });

        lbl_error_numero_cartaporte_editar.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_numero_cartaporte_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_numero_cartaporte_editar.setText("¡Debe ingresar un número de carta de porte!");

        numero_cartaporte_editar.setForeground(new java.awt.Color(0, 0, 0));
        numero_cartaporte_editar.setColorMaterial(new java.awt.Color(99, 70, 250));
        numero_cartaporte_editar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        numero_cartaporte_editar.setPlaceholder("Número de carta de porte...");
        numero_cartaporte_editar.setSelectionColor(new java.awt.Color(220, 23, 111));
        numero_cartaporte_editar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numero_cartaporte_editarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numero_cartaporte_editarKeyTyped(evt);
            }
        });

        id_cartaporte.setText("jLabel1");

        numero_cartaporte_control.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_busca_cartaporte_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_error_pdf_cartaporte_editar)
                                .addGap(399, 399, 399)
                                .addComponent(id_cartaporte)
                                .addGap(53, 53, 53)
                                .addComponent(numero_cartaporte_control))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_foto)
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_error_numero_cartaporte_editar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numero_cartaporte_editar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_guardar_cartaporte_editar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(numero_cartaporte_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbl_error_numero_cartaporte_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(boton_guardar_cartaporte_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(boton_busca_cartaporte_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_error_pdf_cartaporte_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_cartaporte)
                    .addComponent(numero_cartaporte_control))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout rSPanelShadow1Layout = new javax.swing.GroupLayout(rSPanelShadow1);
        rSPanelShadow1.setLayout(rSPanelShadow1Layout);
        rSPanelShadow1Layout.setHorizontalGroup(
            rSPanelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelShadow1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE))
        );
        rSPanelShadow1Layout.setVerticalGroup(
            rSPanelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelShadow1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rSPanelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addEventKey() {
        KeyStroke escape = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0, false);
        Action escapeAction = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        };
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(escape, "ESCAPE");
        getRootPane().getActionMap().put("ESCAPE", escapeAction);
//----------------------------------------------------------------------------------------------
         KeyStroke enter = KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, false);
        Action enterAction = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                boton_guardar_cartaporte_editarActionPerformed(e);
            }
        };
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(enter, "ENTER");
        getRootPane().getActionMap().put("ENTER", enterAction);
        
       
    }
    
    private void deshabilitarPegar() {
        InputMap map2 = numero_cartaporte_editar.getInputMap(numero_cartaporte_editar.WHEN_FOCUSED);
        map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    }
             
    
    private void boton_busca_cartaporte_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_busca_cartaporte_editarActionPerformed
        // TODO add your handling code here:
        try{
            JFileChooser j = new JFileChooser();
            FileNameExtensionFilter fi = new FileNameExtensionFilter("pdf", "pdf");
            j.setFileFilter(fi);
            int se = j.showOpenDialog(this);
            if (se == 0) {
                this.boton_busca_cartaporte_editar.setText("" + j.getSelectedFile().getName());
                ruta_archivo = j.getSelectedFile().getAbsolutePath();

                lb_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_planos/pdf2.png")));
                lbl_error_pdf_cartaporte_editar.setVisible(false);
            }
        }catch(Exception ex){
            opciones_de_gestionar_contrato.lanza_error(ex);
        }
    }//GEN-LAST:event_boton_busca_cartaporte_editarActionPerformed

    Tabla_PdfVO_cartaporte tpdf = new Tabla_PdfVO_cartaporte();
    private void boton_guardar_cartaporte_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardar_cartaporte_editarActionPerformed
        String sql="select * from cartaportes where numero_cartaporte='"+numero_cartaporte_editar.getText()+"'";
        String mje1="Ya existe una carta de porte con ese número("+numero_cartaporte_editar.getText()+")";
        String mje2="¿Desea guardarla de todas formas?";
        String mje3="La base de datos contendrá más de una carta de porte con el mismo número";
        if (numero_cartaporte_editar.getText().isEmpty()) {
                lbl_error_numero_cartaporte_editar.setVisible(true);
        } else {
            if (interaccion_bd.opciones_de_gestionar_contrato.existe(numero_cartaporte_editar.getText(), sql) && !numero_cartaporte_control.getText().equals(numero_cartaporte_editar.getText())) {
                WarningAlert a=new WarningAlert(new JFrame(), true);
                a.msj1.setText(mje1);
                a.msj2.setText(mje2);
                a.msj3.setText(mje3);
                a.preferredSize();
                a.pack();
                a.setVisible(true);
                if(a.hecho==false){
                    numero_cartaporte_editar.requestFocus();
                }else{
                    
                    
                     Runnable runnable1 = new Runnable() {
                    public void run() {
                        Guardando_general l = new Guardando_general(new JFrame(), true);
                        l.setLocationRelativeTo(paneles_de_paneles.de_gestionar_cartaporte_editar.this);
                        l.setVisible(true);
                        try{
                            de_gestionar_cartaporte_editar.this.setEnabled(false);
                            
                            modificar();
                            SuccessAlert e = new SuccessAlert(new JFrame(), true);
                            e.msj1.setText("¡Los datos de la carta de porte fueron");
                            e.msj2.setText("guardados exitosamente!.");
                            e.msj3.setText("");
                            e.setVisible(true);
                            de_gestionar_cartaporte_editar.this.setEnabled(true);
                            l.setVisible(false);
                        }catch(Exception e){
                            Logger.getLogger(opciones_de_gestionar_contrato.class.getName()).log(Level.SEVERE, null, e);
                            opciones_de_gestionar_contrato.lanza_error(e);
                        }
                    }
                };
                Thread t1 = new Thread(runnable1);
                t1.start();
                    
                    
                }
            }else{
                    
                Runnable runnable1 = new Runnable() {
                    public void run() {
                        Guardando_general l = new Guardando_general(new JFrame(), true);
                        l.setLocationRelativeTo(paneles_de_paneles.de_gestionar_cartaporte_editar.this);
                        l.setVisible(true);
                        try{
                            paneles_de_paneles.de_gestionar_cartaporte_editar.this.setEnabled(false);
                            
                            modificar();
                            SuccessAlert e = new SuccessAlert(new JFrame(), true);
                            e.msj1.setText("¡Los datos de la carta de porte fueron");
                            e.msj2.setText("guardados exitosamente!.");
                            e.msj3.setText("");
                            e.setVisible(true);
                            de_gestionar_cartaporte_editar.this.setEnabled(true);
                            l.setVisible(false);
                        }catch(Exception e){
                            Logger.getLogger(opciones_de_gestionar_contrato.class.getName()).log(Level.SEVERE, null, e);
                            opciones_de_gestionar_contrato.lanza_error(e);
                        }
                    }
                };
                Thread t1 = new Thread(runnable1);
                t1.start();
                
                    }     
         }
        this.dispose();
    }//GEN-LAST:event_boton_guardar_cartaporte_editarActionPerformed

    private void modificar() {                                             
        String numero = numero_cartaporte_editar.getText();
        File ruta = new File(ruta_archivo);
        if (numero.trim().length() != 0 && ruta_archivo.trim().length() != 0) {
            modificar_pdf(Integer.parseInt(id_cartaporte.getText()), numero, ruta);
            tpdf.visualizar_PdfVO(de_gestionar_cartaporte_listar.tabla_cartaporte);
        } else if (ruta_archivo.trim().length() == 0) {
            modificar_pdf(Integer.parseInt(id_cartaporte.getText()), numero);
            tpdf.visualizar_PdfVO(de_gestionar_cartaporte_listar.tabla_cartaporte);
        }
        ruta_archivo = "";
        de_gestionar_cartaporte_listar.tabla_cartaporte.setDefaultRenderer(Object.class, new modelo_tablas.Tabla_Planos());
    } 
    
    public void modificar_pdf(int codigo, String nombre, File ruta) {
        PdfDAO_cartaporte pa = new PdfDAO_cartaporte();
        PdfVO_cartaporte po = new PdfVO_cartaporte();
        po.setCodigopdf(codigo);
        po.setNombrepdf(nombre);
        try {
            byte[] pdf = new byte[(int) ruta.length()];
            InputStream input = new FileInputStream(ruta);
            input.read(pdf);
            po.setArchivopdf(pdf);
        } catch (IOException ex) {
            po.setArchivopdf(null);
            //System.out.println("Error al agregar archivo pdf "+ex.getMessage());
        }
        pa.Modificar_PdfVO(po);
    }

    public void modificar_pdf(int codigo, String nombre) {
        PdfDAO_cartaporte pa = new PdfDAO_cartaporte();
        PdfVO_cartaporte po = new PdfVO_cartaporte();
        po.setCodigopdf(codigo);
        po.setNombrepdf(nombre);
        pa.Modificar_PdfVO2(po);
    }
    
    private void numero_cartaporte_editarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numero_cartaporte_editarKeyReleased
        // TODO add your handling code here:
        if(numero_cartaporte_editar.getText().length()>0){
            lbl_error_numero_cartaporte_editar.setVisible(false);
        }
    }//GEN-LAST:event_numero_cartaporte_editarKeyReleased

    private void numero_cartaporte_editarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numero_cartaporte_editarKeyTyped
        // TODO add your handling code here:
        if(numero_cartaporte_editar.getText().length()<6){
        char num = evt.getKeyChar();
        if ((num < '0' || num > '9')) {
            evt.consume();
        }
        }else{
             evt.consume();
        }
    }//GEN-LAST:event_numero_cartaporte_editarKeyTyped

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(de_gestionar_cartaporte_editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(de_gestionar_cartaporte_editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(de_gestionar_cartaporte_editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(de_gestionar_cartaporte_editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                de_gestionar_cartaporte_editar dialog = new de_gestionar_cartaporte_editar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple boton_busca_cartaporte_editar;
    private rojeru_san.RSButtonRiple boton_guardar_cartaporte_editar;
    public static javax.swing.JLabel id_cartaporte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_foto;
    private javax.swing.JLabel lbl_error_numero_cartaporte_editar;
    private javax.swing.JLabel lbl_error_pdf_cartaporte_editar;
    public static javax.swing.JLabel numero_cartaporte_control;
    public static rojeru_san.rsfield.RSTextMaterial numero_cartaporte_editar;
    private rojeru_san.rspanel.RSPanelShadow rSPanelShadow1;
    // End of variables declaration//GEN-END:variables
}
