/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles_de_paneles;

import alertas.SuccessAlert;
import esperas.Guardando_general;
import interaccion_bd.consultas_de_gestionar_recursos_x_programa;
import interaccion_bd.opciones_de_gestionar_contrato;
import interaccion_bd.opciones_de_gestionar_prod_programa;
import interaccion_bd.opciones_de_gestionar_recursos_x_programa;
import java.awt.Event;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import javax.swing.InputMap;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author RojeruSan
 */
public class de_gestionar_recursos_x_programa_añadir extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public de_gestionar_recursos_x_programa_añadir() {
        initComponents();
        lbl_error_descripcion_re_add.setVisible(false);
        lbl_error_cant_re_add.setVisible(false);
        lbl_error_programa_re_add.setVisible(false);
        lbl_error_factura_re_add.setVisible(false);
        lbl_error_carta_porte_add.setVisible(false);
        codigo_re_add.setEnabled(false);
        um_re_add.setEnabled(false);
        deshabilitarPegar();
        opciones_de_gestionar_recursos_x_programa.get_combos(combo_prefabricados_re_add, combo_programas_re_add);
        //################### detectar cambios en los combobox ######################3
        combo_prefabricados_re_add.addItemListener(new ItemListener() {
           public void itemStateChanged(ItemEvent arg0) {
               //Do Something
              lbl_error_descripcion_re_add.setVisible(false);
           }
           
            public void itemStateChangedd(ItemEvent e) {
             //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
       });
        
        combo_programas_re_add.addItemListener(new ItemListener() {
           public void itemStateChanged(ItemEvent arg0) {
               //Do Something
              lbl_error_programa_re_add.setVisible(false);
           }
           
            public void itemStateChangedd(ItemEvent e) {
             //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
       });
        // ##########################################################################
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cantidad_re_add = new rojeru_san.rsfield.RSTextMaterial();
        lbl_error_descripcion_re_add = new javax.swing.JLabel();
        lbl_error_cant_re_add = new javax.swing.JLabel();
        boton_guardar_recursos_x_programa_add = new rojeru_san.RSButtonRiple();
        um_re_add = new rojeru_san.rsfield.RSTextMaterial();
        codigo_re_add = new rojeru_san.rsfield.RSTextMaterial();
        factura_re_add = new rojeru_san.rsfield.RSTextMaterial();
        lbl_error_factura_re_add = new javax.swing.JLabel();
        lbl_error_programa_re_add = new javax.swing.JLabel();
        carta_porte_re_add = new rojeru_san.rsfield.RSTextMaterial();
        lbl_error_carta_porte_add = new javax.swing.JLabel();
        combo_programas_re_add = new org.bolivia.combo.SComboBox();
        check_programas = new check_de_android.Switch();
        combo_prefabricados_re_add = new org.bolivia.combo.SComboBox();
        check_prefabricados = new check_de_android.Switch();
        check_fijar = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_recursos_x_programa/recursos.jpg"))); // NOI18N

        cantidad_re_add.setForeground(new java.awt.Color(0, 0, 0));
        cantidad_re_add.setColorMaterial(new java.awt.Color(99, 70, 250));
        cantidad_re_add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cantidad_re_add.setPlaceholder("Cantidad...");
        cantidad_re_add.setSelectionColor(new java.awt.Color(220, 23, 111));
        cantidad_re_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cantidad_re_addKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidad_re_addKeyTyped(evt);
            }
        });

        lbl_error_descripcion_re_add.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_descripcion_re_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_descripcion_re_add.setText("¡Debe ingresar una descripcion del recurso!");

        lbl_error_cant_re_add.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_cant_re_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_cant_re_add.setText("¡Debe ingresar una cantidad!");

        boton_guardar_recursos_x_programa_add.setBackground(new java.awt.Color(38, 86, 186));
        boton_guardar_recursos_x_programa_add.setText("Guardar Cambios");
        boton_guardar_recursos_x_programa_add.setColorHover(new java.awt.Color(173, 187, 194));
        boton_guardar_recursos_x_programa_add.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_guardar_recursos_x_programa_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardar_recursos_x_programa_addActionPerformed(evt);
            }
        });

        um_re_add.setForeground(new java.awt.Color(0, 0, 0));
        um_re_add.setColorMaterial(new java.awt.Color(99, 70, 250));
        um_re_add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        um_re_add.setPlaceholder("Unidad de medida... (autocompletable)");
        um_re_add.setSelectionColor(new java.awt.Color(220, 23, 111));

        codigo_re_add.setForeground(new java.awt.Color(0, 0, 0));
        codigo_re_add.setColorMaterial(new java.awt.Color(99, 70, 250));
        codigo_re_add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        codigo_re_add.setPlaceholder("Código del recurso...  (autocompletable)");
        codigo_re_add.setSelectionColor(new java.awt.Color(220, 23, 111));
        codigo_re_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigo_re_addKeyTyped(evt);
            }
        });

        factura_re_add.setForeground(new java.awt.Color(0, 0, 0));
        factura_re_add.setColorMaterial(new java.awt.Color(99, 70, 250));
        factura_re_add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        factura_re_add.setPlaceholder("Número de factura...");
        factura_re_add.setSelectionColor(new java.awt.Color(220, 23, 111));
        factura_re_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                factura_re_addKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                factura_re_addKeyTyped(evt);
            }
        });

        lbl_error_factura_re_add.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_factura_re_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_factura_re_add.setText("¡Debe ingresar un número de factura!");

        lbl_error_programa_re_add.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_programa_re_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_programa_re_add.setText("¡Debe ingresar un programa!");

        carta_porte_re_add.setForeground(new java.awt.Color(0, 0, 0));
        carta_porte_re_add.setColorMaterial(new java.awt.Color(99, 70, 250));
        carta_porte_re_add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        carta_porte_re_add.setPlaceholder("Número de carta porte...");
        carta_porte_re_add.setSelectionColor(new java.awt.Color(220, 23, 111));
        carta_porte_re_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                carta_porte_re_addKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                carta_porte_re_addKeyTyped(evt);
            }
        });

        lbl_error_carta_porte_add.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_carta_porte_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_carta_porte_add.setText("¡Debe ingresar un número de carta porte!");

        combo_programas_re_add.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PROGRAMA" }));

        check_programas.setToolTipText("Hacer o deshacer editable");
        check_programas.setBackgroundColor(new java.awt.Color(38, 86, 186));
        check_programas.setOnOff(false);
        check_programas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check_programasMouseClicked(evt);
            }
        });

        combo_prefabricados_re_add.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MATERIALES" }));
        combo_prefabricados_re_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_prefabricados_re_addActionPerformed(evt);
            }
        });

        check_prefabricados.setToolTipText("Hacer o deshacer editable");
        check_prefabricados.setBackgroundColor(new java.awt.Color(38, 86, 186));
        check_prefabricados.setOnOff(false);
        check_prefabricados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check_prefabricadosMouseClicked(evt);
            }
        });

        check_fijar.setBorder(null);
        check_fijar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        check_fijar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_recursos_x_programa/fijado_off_ok.png"))); // NOI18N
        check_fijar.setOpaque(false);
        check_fijar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img_recursos_x_programa/fijado_on_ok.png"))); // NOI18N
        check_fijar.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(check_fijar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_error_programa_re_add)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(factura_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(carta_porte_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(combo_programas_re_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(check_programas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbl_error_factura_re_add)
                            .addComponent(lbl_error_carta_porte_add))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(boton_guardar_recursos_x_programa_add, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_error_descripcion_re_add)
                            .addComponent(um_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidad_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(combo_prefabricados_re_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(check_prefabricados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(codigo_re_add, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lbl_error_cant_re_add))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(combo_programas_re_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(check_programas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lbl_error_programa_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(check_fijar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(codigo_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo_prefabricados_re_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(check_prefabricados, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_error_descripcion_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(um_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cantidad_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_error_cant_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_error_factura_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(factura_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carta_porte_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_guardar_recursos_x_programa_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(lbl_error_carta_porte_add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cantidad_re_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidad_re_addKeyReleased
        // TODO add your handling code here:
        if(cantidad_re_add.getText().length()>0){
            lbl_error_cant_re_add.setVisible(false);
        }
    }//GEN-LAST:event_cantidad_re_addKeyReleased

    private void cantidad_re_addKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidad_re_addKeyTyped
        // TODO add your handling code here:
        char num = evt.getKeyChar();
        if ((num < '0' || num > '9')) {
            evt.consume();

        }
    }//GEN-LAST:event_cantidad_re_addKeyTyped

    private void boton_guardar_recursos_x_programa_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardar_recursos_x_programa_addActionPerformed
        String sql_elemento="select * from materia_prima where `elem__materia_prima`='"+combo_prefabricados_re_add.getSelectedItem().toString()+"'";
        String sql_programa="SELECT * FROM `contrato` WHERE  `nombre_contrato`='"+combo_programas_re_add.getSelectedItem().toString()+"'";
        String sql_control="select * from recursos_x_programa_control where codigo_re_control='"+codigo_re_add.getText()+"' "
                + "and programa_re_control='"+combo_programas_re_add.getSelectedItem().toString()+"'";
        String sql_agrupa="select * from recursos_x_programa where codigo_re='"+codigo_re_add.getText()+"' "
                + "and programa_re='"+combo_programas_re_add.getSelectedItem().toString()+"'";
//        String mje1="El código de recursos por programa que intenta registrar ya existe";
//        String mje2="Por favor introduzca un código distinto de recurso";
        if (combo_prefabricados_re_add.getSelectedIndex()==0||
                cantidad_re_add.getText().isEmpty()||combo_programas_re_add.getSelectedIndex()==0||factura_re_add.getText().isEmpty()||
                carta_porte_re_add.getText().isEmpty()||opciones_de_gestionar_prod_programa.existe(sql_elemento) == false||opciones_de_gestionar_prod_programa.existe(sql_programa) == false) {
            if(combo_prefabricados_re_add.getSelectedIndex()==0){
                combo_prefabricados_re_add.requestFocus();
                lbl_error_descripcion_re_add.setVisible(true);
            }else if(cantidad_re_add.getText().isEmpty()){
                cantidad_re_add.requestFocus();
                lbl_error_cant_re_add.setVisible(true);
            }else if(combo_programas_re_add.getSelectedIndex()==0){
                combo_programas_re_add.requestFocus();
                lbl_error_programa_re_add.setVisible(true);
            }else if(factura_re_add.getText().isEmpty()){
                factura_re_add.requestFocus();
                lbl_error_factura_re_add.setVisible(true);
            }else if(carta_porte_re_add.getText().isEmpty()){
                carta_porte_re_add.requestFocus();
                lbl_error_carta_porte_add.setVisible(true);
            }else if(opciones_de_gestionar_prod_programa.existe(sql_elemento) == false){
            opciones_de_gestionar_contrato.lanza_error_variable_sin_ex("El elemento descrito no se encuentra en la base de datos.",
                "Por favor, elija uno de los existentes en nuestra base de datos.",
                "");
            combo_prefabricados_re_add.requestFocus();
            }else if(opciones_de_gestionar_prod_programa.existe(sql_programa) == false){
            opciones_de_gestionar_contrato.lanza_error_variable_sin_ex("El programa descrito no se encuentra en la base de datos.",
                "Por favor, si es real, regístrelo antes de volver a intentarlo.",
                "De lo contrario seleccione uno existente en nuestra base de datos");
            combo_programas_re_add.requestFocus();
            }        } else {

//                if (interaccion_bd.opciones_de_gestionar_contrato.existe(codigo_re_add.getText(), sql)) {
//                    opciones_de_gestionar_contrato.lanza_error_variable_sin_ex("",mje1,mje2);
//                    cantidad_re_add.requestFocus();
//                }else{
                    Guardando_general l = new Guardando_general(new JFrame(), true);
                    consultas_de_gestionar_recursos_x_programa uc=new consultas_de_gestionar_recursos_x_programa();
                    l.setLocationRelativeTo(paneles_de_paneles.de_gestionar_recursos_x_programa_añadir.this);
                    l.setVisible(true);
                    paneles_de_paneles.de_gestionar_recursos_x_programa_añadir.this.setEnabled(false);
                    uc.setCodigo(codigo_re_add.getText());
                uc.setDescripcion(combo_prefabricados_re_add.getSelectedItem().toString());
                uc.setUm(um_re_add.getText());
                uc.setCant(cantidad_re_add.getText());
                uc.setPrograma_pertenece(combo_programas_re_add.getSelectedItem().toString());
                uc.setFactura(factura_re_add.getText());
                uc.setCarta_porte(carta_porte_re_add.getText());
                    int control= opciones_de_gestionar_recursos_x_programa.registrar(uc);
                    
                    paneles_de_paneles.de_gestionar_recursos_x_programa_añadir.this.setEnabled(true);
                    l.setVisible(false);
                    if(control==1){
                        reset_campos();
                        opciones_de_gestionar_recursos_x_programa.setListar("");
                        SuccessAlert e = new SuccessAlert(new JFrame(), true);
                        e.msj1.setText("¡Los datos del recurso fueron");
                        e.msj2.setText("guardados exitosamente!.");
                        e.msj3.setText("");
                        e.setVisible(true);
                    }
//                }
            
        }
    }//GEN-LAST:event_boton_guardar_recursos_x_programa_addActionPerformed

    private void factura_re_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_factura_re_addKeyReleased
        // TODO add your handling code here:
        if(factura_re_add.getText().length()>0){
            lbl_error_factura_re_add.setVisible(false);
        }
    }//GEN-LAST:event_factura_re_addKeyReleased

    private void factura_re_addKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_factura_re_addKeyTyped
        // TODO add your handling code here:
        char num = evt.getKeyChar();
        if ((num < '0' || num > '9')) {
            evt.consume();
            
        }
    }//GEN-LAST:event_factura_re_addKeyTyped

    private void carta_porte_re_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carta_porte_re_addKeyReleased
        // TODO add your handling code here:
        if(carta_porte_re_add.getText().length()>0){
            lbl_error_carta_porte_add.setVisible(false);
        }
    }//GEN-LAST:event_carta_porte_re_addKeyReleased

    private void carta_porte_re_addKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carta_porte_re_addKeyTyped
        // TODO add your handling code here:
        char num = evt.getKeyChar();
        if ((num < '0' || num > '9')) {
            evt.consume();
            
        }
    }//GEN-LAST:event_carta_porte_re_addKeyTyped

    private void check_programasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check_programasMouseClicked
        // TODO add your handling code here:
        if(check_programas.isOnOff()){
            combo_programas_re_add.setEditable(true);
            AutoCompleteDecorator.decorate(combo_programas_re_add);
        }else{
            combo_programas_re_add.setEditable(false);
            combo_programas_re_add.requestFocus();
        }
    }//GEN-LAST:event_check_programasMouseClicked

    private void check_prefabricadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check_prefabricadosMouseClicked
        // TODO add your handling code here:
        if(check_prefabricados.isOnOff()){
            combo_prefabricados_re_add.setEditable(true);
            AutoCompleteDecorator.decorate(combo_prefabricados_re_add);
        }else{
            combo_prefabricados_re_add.setEditable(false);
            combo_prefabricados_re_add.requestFocus();
        }
    }//GEN-LAST:event_check_prefabricadosMouseClicked

    private void codigo_re_addKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigo_re_addKeyTyped
        // TODO add your handling code here:
        char num = evt.getKeyChar();
        if ((num < '0' || num > '9')) {
            evt.consume();

        }
    }//GEN-LAST:event_codigo_re_addKeyTyped

    private void combo_prefabricados_re_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_prefabricados_re_addActionPerformed
        // TODO add your handling code here:
        String sql_codigo="SELECT `codigo_materia_prima` FROM `materia_prima` WHERE `elem__materia_prima`='"+combo_prefabricados_re_add.getSelectedItem().toString().trim()+"'";
        String sql_um="SELECT `um_materia_prima` FROM `materia_prima` WHERE `elem__materia_prima`='"+combo_prefabricados_re_add.getSelectedItem().toString().trim()+"'";
        um_re_add.setText(opciones_de_gestionar_recursos_x_programa.extraer_id(sql_um));
        codigo_re_add.setText(opciones_de_gestionar_recursos_x_programa.extraer_id(sql_codigo));
    }//GEN-LAST:event_combo_prefabricados_re_addActionPerformed

     private void deshabilitarPegar() {
        InputMap map1 = codigo_re_add.getInputMap(codigo_re_add.WHEN_FOCUSED);
        map1.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");

        
        InputMap map3 = um_re_add.getInputMap(um_re_add.WHEN_FOCUSED);
        map3.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
        InputMap map4 = cantidad_re_add.getInputMap(cantidad_re_add.WHEN_FOCUSED);
        map4.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
        
        InputMap map6 = factura_re_add.getInputMap(factura_re_add.WHEN_FOCUSED);
        map6.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
        InputMap map7 = carta_porte_re_add.getInputMap(carta_porte_re_add.WHEN_FOCUSED);
        map7.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    }

    private void reset_campos(){
        cantidad_re_add.setText("");
        combo_prefabricados_re_add.setSelectedIndex(0);
        codigo_re_add.setText("");
        um_re_add.setText("");
        if(!check_fijar.isSelected()){
            combo_programas_re_add.setSelectedIndex(0);
        }
        factura_re_add.setText("");
        carta_porte_re_add.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple boton_guardar_recursos_x_programa_add;
    public static rojeru_san.rsfield.RSTextMaterial cantidad_re_add;
    public static rojeru_san.rsfield.RSTextMaterial carta_porte_re_add;
    private javax.swing.JCheckBox check_fijar;
    private check_de_android.Switch check_prefabricados;
    private check_de_android.Switch check_programas;
    public static rojeru_san.rsfield.RSTextMaterial codigo_re_add;
    private org.bolivia.combo.SComboBox combo_prefabricados_re_add;
    private org.bolivia.combo.SComboBox combo_programas_re_add;
    public static rojeru_san.rsfield.RSTextMaterial factura_re_add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_error_cant_re_add;
    private javax.swing.JLabel lbl_error_carta_porte_add;
    private javax.swing.JLabel lbl_error_descripcion_re_add;
    private javax.swing.JLabel lbl_error_factura_re_add;
    private javax.swing.JLabel lbl_error_programa_re_add;
    public static rojeru_san.rsfield.RSTextMaterial um_re_add;
    // End of variables declaration//GEN-END:variables
}
