/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles_de_paneles;

import alertas.ErrorAlert;
import alertas.SuccessAlert;
import com.toedter.calendar.JDateChooser;
import esperas.Guardando_general;
import interaccion_bd.consultas_de_gestionar_contrato;
import interaccion_bd.consultas_de_gestionar_tarj_combustible;
import interaccion_bd.opciones_de_gestionar_contrato;
import interaccion_bd.opciones_de_gestionar_tarj_combustible;
import java.awt.Event;
import paneles.*;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.lang.reflect.Field;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import static paneles_de_paneles.de_gestionar_contrato_editar.nombre_cliente_contrato_editar;
import static paneles_de_paneles.de_gestionar_contrato_editar.numero_contrato_editar;

/**
 *
 * @author RojeruSan
 */
public class de_gestionar_info_laboratorio_añadir extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public de_gestionar_info_laboratorio_añadir() {
        initComponents();
        lbl_error_cant_litro_tarjeta.setVisible(false);
        lbl_error_numero_tarjeta.setVisible(false);
        lbl_error_fecha_asignacion_tarjeta.setVisible(false);
        lbl_error_tipo_combustible.setVisible(false);
        lbl_error_ping_tarjeta.setVisible(false);
        lbl_error_numero_chapa.setVisible(false);

      //  detectar cambio en jdateChoser (fecha de inicio en agregar contrato)
        fecha_iasignacion_tarjeta.getDateEditor().addPropertyChangeListener(
                new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent e) {
                if ("date".equals(e.getPropertyName())) {
                    System.out.println(e.getPropertyName()
                            + ": " + (Date) e.getNewValue());
                    if(fecha_iasignacion_tarjeta.getDate()==null){
                    lbl_error_fecha_asignacion_tarjeta.setVisible(true);
                    }
                }else{
                    lbl_error_fecha_asignacion_tarjeta.setVisible(false);
                }
            }
        });
        this.add(fecha_iasignacion_tarjeta);
        
         //################### detectar cambios en los combobox ######################3
        combo_tipo_combustible.addItemListener(new ItemListener() {
           public void itemStateChanged(ItemEvent arg0) {
               //Do Something
              lbl_error_tipo_combustible.setVisible(false);
           }
           
            public void itemStateChangedd(ItemEvent e) {
             //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
       });
        // ##########################################################################
        
        
        deshabilitarPegar();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        numero_tarjeta_tarjeta = new rojeru_san.rsfield.RSTextMaterial();
        lbl_error_numero_tarjeta = new javax.swing.JLabel();
        ping_tarjeta = new rojeru_san.rsfield.RSTextMaterial();
        lbl_error_ping_tarjeta = new javax.swing.JLabel();
        numero_cant_litros_tarjeta = new rojeru_san.rsfield.RSTextMaterial();
        lbl_error_cant_litro_tarjeta = new javax.swing.JLabel();
        lbl_error_numero_chapa = new javax.swing.JLabel();
        fecha_iasignacion_tarjeta = new com.toedter.calendar.JDateChooser();
        lbl_error_fecha_asignacion_tarjeta = new javax.swing.JLabel();
        lbl_error_tipo_combustible = new javax.swing.JLabel();
        combo_tipo_combustible = new org.bolivia.combo.SComboBox();
        boton_guardar_tarjeta = new rojeru_san.RSButtonRiple();
        numero_chapa_tarjeta = new rojeru_san.rsfield.RSTextMaterial();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_tarj_combustible/tarjeta_combustible3.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        numero_tarjeta_tarjeta.setForeground(new java.awt.Color(0, 0, 0));
        numero_tarjeta_tarjeta.setColorMaterial(new java.awt.Color(99, 70, 250));
        numero_tarjeta_tarjeta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        numero_tarjeta_tarjeta.setPlaceholder("Número de tarjeta...");
        numero_tarjeta_tarjeta.setSelectionColor(new java.awt.Color(220, 23, 111));
        numero_tarjeta_tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_tarjeta_tarjetaActionPerformed(evt);
            }
        });
        numero_tarjeta_tarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numero_tarjeta_tarjetaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numero_tarjeta_tarjetaKeyTyped(evt);
            }
        });

        lbl_error_numero_tarjeta.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_numero_tarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_numero_tarjeta.setText("¡Debe ingresar número de tarjeta!");

        ping_tarjeta.setForeground(new java.awt.Color(0, 0, 0));
        ping_tarjeta.setColorMaterial(new java.awt.Color(99, 70, 250));
        ping_tarjeta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ping_tarjeta.setPlaceholder("Ping de tarjeta...");
        ping_tarjeta.setSelectionColor(new java.awt.Color(220, 23, 111));
        ping_tarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ping_tarjetaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ping_tarjetaKeyTyped(evt);
            }
        });

        lbl_error_ping_tarjeta.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_ping_tarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_ping_tarjeta.setText("¡Debe ingresar ping de tarjeta!");

        numero_cant_litros_tarjeta.setForeground(new java.awt.Color(0, 0, 0));
        numero_cant_litros_tarjeta.setColorMaterial(new java.awt.Color(99, 70, 250));
        numero_cant_litros_tarjeta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        numero_cant_litros_tarjeta.setPlaceholder("Cantidad de litros...");
        numero_cant_litros_tarjeta.setSelectionColor(new java.awt.Color(220, 23, 111));
        numero_cant_litros_tarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numero_cant_litros_tarjetaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numero_cant_litros_tarjetaKeyTyped(evt);
            }
        });

        lbl_error_cant_litro_tarjeta.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_cant_litro_tarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_cant_litro_tarjeta.setText("¡Debe ingresar una cantidad de litros!");

        lbl_error_numero_chapa.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_numero_chapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_numero_chapa.setText("¡Debe ingresar número de chapa!");

        fecha_iasignacion_tarjeta.setDateFormatString("dd/MM/yyyy");
        fecha_iasignacion_tarjeta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fecha_iasignacion_tarjeta.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                fecha_iasignacion_tarjetaAncestorRemoved(evt);
            }
        });

        lbl_error_fecha_asignacion_tarjeta.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_fecha_asignacion_tarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_fecha_asignacion_tarjeta.setText("¡Debe ingresar una fecha!");

        lbl_error_tipo_combustible.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_tipo_combustible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_tipo_combustible.setText("¡Debe ingresar un tipo de combustible!");

        combo_tipo_combustible.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TIPO COMBUSTIBLE", "GASOLINA", "PETRÓLEO" }));

        boton_guardar_tarjeta.setBackground(new java.awt.Color(38, 86, 186));
        boton_guardar_tarjeta.setText("Guardar Tarjeta");
        boton_guardar_tarjeta.setColorHover(new java.awt.Color(173, 187, 194));
        boton_guardar_tarjeta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_guardar_tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardar_tarjetaActionPerformed(evt);
            }
        });

        numero_chapa_tarjeta.setForeground(new java.awt.Color(0, 0, 0));
        numero_chapa_tarjeta.setColorMaterial(new java.awt.Color(99, 70, 250));
        numero_chapa_tarjeta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        numero_chapa_tarjeta.setPlaceholder("Chapa a la que pertenece...");
        numero_chapa_tarjeta.setSelectionColor(new java.awt.Color(220, 23, 111));
        numero_chapa_tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_chapa_tarjetaActionPerformed(evt);
            }
        });
        numero_chapa_tarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numero_chapa_tarjetaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numero_chapa_tarjetaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numero_tarjeta_tarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(lbl_error_numero_tarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_error_numero_chapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fecha_iasignacion_tarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_error_fecha_asignacion_tarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numero_chapa_tarjeta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_error_tipo_combustible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_error_ping_tarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ping_tarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numero_cant_litros_tarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combo_tipo_combustible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_error_cant_litro_tarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(boton_guardar_tarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(134, 134, 134)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ping_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero_tarjeta_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_error_numero_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_error_ping_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero_chapa_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero_cant_litros_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_error_numero_chapa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_error_cant_litro_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fecha_iasignacion_tarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(combo_tipo_combustible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_error_fecha_asignacion_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_error_tipo_combustible, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(boton_guardar_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

     private void deshabilitarPegar() {
        InputMap map1 = numero_tarjeta_tarjeta.getInputMap(numero_tarjeta_tarjeta.WHEN_FOCUSED);
        map1.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");

        InputMap map2 = numero_cant_litros_tarjeta.getInputMap(numero_cant_litros_tarjeta.WHEN_FOCUSED);
        map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
        InputMap map3 = ping_tarjeta.getInputMap(ping_tarjeta.WHEN_FOCUSED);
        map3.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
        InputMap map4= numero_chapa_tarjeta.getInputMap(numero_chapa_tarjeta.WHEN_FOCUSED);
        map4.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    }
    
    private void numero_tarjeta_tarjetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numero_tarjeta_tarjetaKeyReleased
        // TODO add your handling code here:
        if(numero_tarjeta_tarjeta.getText().length()>0){
            lbl_error_numero_tarjeta.setVisible(false);
        }

    }//GEN-LAST:event_numero_tarjeta_tarjetaKeyReleased

    private void numero_cant_litros_tarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numero_cant_litros_tarjetaKeyTyped
        // TODO add your handling code here:
        if(numero_cant_litros_tarjeta.getText().length()<10){
        char num = evt.getKeyChar();
        if ((num < '0' || num > '9')) {
            evt.consume();
        }
        }else{
            evt.consume();
        }
    }//GEN-LAST:event_numero_cant_litros_tarjetaKeyTyped

    private void numero_tarjeta_tarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numero_tarjeta_tarjetaKeyTyped
        // TODO add your handling code here:
        if(numero_tarjeta_tarjeta.getText().length()<16){
        char num = evt.getKeyChar();
        if ((num < '0' || num > '9')) {
            evt.consume();
            
        }
        }else{
            evt.consume();
        }
    }//GEN-LAST:event_numero_tarjeta_tarjetaKeyTyped

    private void numero_cant_litros_tarjetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numero_cant_litros_tarjetaKeyReleased
        // TODO add your handling code here:
        if(numero_cant_litros_tarjeta.getText().length()>0){
        lbl_error_cant_litro_tarjeta.setVisible(false);
    }
    }//GEN-LAST:event_numero_cant_litros_tarjetaKeyReleased

    private void boton_guardar_tarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardar_tarjetaActionPerformed
      String sql="SELECT * FROM `tarj_combustible` WHERE `numero_tarj`='"+numero_tarjeta_tarjeta+"'";
      String mje1="La tarjeta que intenta introducir al sistema ya existe";
      String mje2="Por favor introduzca una nueva";
        if (numero_tarjeta_tarjeta.getText().isEmpty()||combo_tipo_combustible.getSelectedIndex()==0 || 
                ping_tarjeta.getText().isEmpty()|| numero_chapa_tarjeta.getText().isEmpty()|| 
                numero_cant_litros_tarjeta.getText().isEmpty() ||fecha_iasignacion_tarjeta.getDate()==null ||
                interaccion_bd.opciones_de_gestionar_contrato.existe(numero_tarjeta_tarjeta.getText(), sql)||
                numero_tarjeta_tarjeta.getText().length()<16 || ping_tarjeta.getText().length()<4 || 
                numero_chapa_tarjeta.getText().length()<7) {
            if(numero_tarjeta_tarjeta.getText().isEmpty()){
                numero_tarjeta_tarjeta.requestFocus();
                lbl_error_numero_tarjeta.setText("¡Debe ingresar número de tarjeta!");
                lbl_error_numero_tarjeta.setVisible(true);
            }else if(ping_tarjeta.getText().isEmpty()){
                ping_tarjeta.requestFocus();
                lbl_error_ping_tarjeta.setText("¡Debe ingresar ping de tarjeta!");
                lbl_error_ping_tarjeta.setVisible(true);
            }else if(numero_chapa_tarjeta.getText().isEmpty()){
                numero_chapa_tarjeta.requestFocus();
                lbl_error_numero_chapa.setText("¡Debe ingresar número de chapa!");
                lbl_error_numero_chapa.setVisible(true);
            }else if(numero_cant_litros_tarjeta.getText().isEmpty()){
                numero_cant_litros_tarjeta.requestFocus();
                lbl_error_cant_litro_tarjeta.setVisible(true);
            }else if(fecha_iasignacion_tarjeta.getDate()==null){
                fecha_iasignacion_tarjeta.requestFocus();
                lbl_error_fecha_asignacion_tarjeta.setVisible(true);
            }else if(combo_tipo_combustible.getSelectedIndex()==0){
                combo_tipo_combustible.requestFocus();
                lbl_error_tipo_combustible.setVisible(true);
            }else if (interaccion_bd.opciones_de_gestionar_contrato.existe(numero_tarjeta_tarjeta.getText(), sql)) {
                            opciones_de_gestionar_contrato.lanza_error_variable_sin_ex(mje1,mje2,"");
                            numero_tarjeta_tarjeta.requestFocus();
                        }else if(numero_tarjeta_tarjeta.getText().length()<16){
                numero_tarjeta_tarjeta.requestFocus();
                lbl_error_numero_tarjeta.setText("¡El número debe contener 16 dígitos!");
                lbl_error_numero_tarjeta.setVisible(true);
                        }else if(ping_tarjeta.getText().length()<4){
                ping_tarjeta.requestFocus();
                lbl_error_ping_tarjeta.setText("¡El número debe contener 4 dígitos!");
                lbl_error_ping_tarjeta.setVisible(true);
            }else if(numero_chapa_tarjeta.getText().length()<7){
                numero_chapa_tarjeta.requestFocus();
                lbl_error_numero_chapa.setText("¡El campo debe contener 1 letra y 6 dígitos!");
                lbl_error_numero_chapa.setVisible(true);
            }
        } else {
            Runnable runnable1 = new Runnable() {
                public void run() {
                    Guardando_general l = new Guardando_general(new JFrame(), true);
                    consultas_de_gestionar_tarj_combustible uc=new consultas_de_gestionar_tarj_combustible();
                    l.setLocationRelativeTo(paneles_de_paneles.de_gestionar_info_laboratorio_añadir.this);
                    l.setVisible(true);
                    try{            //toma_fecha()
                    paneles_de_paneles.de_gestionar_info_laboratorio_añadir.this.setEnabled(false);
                    uc.setNumero_tarjeta(numero_tarjeta_tarjeta.getText());
                    uc.setTipo_combustible_tarjeta(combo_tipo_combustible.getSelectedItem().toString());
                    uc.setPing_tarjeta(ping_tarjeta.getText());
                    uc.setChapa_tarjeta(numero_chapa_tarjeta.getText());
                    uc.setCant_litros_tarjeta(numero_cant_litros_tarjeta.getText());
                    uc.setFecha_asignacion_tarjeta(toma_fecha(fecha_iasignacion_tarjeta));
                   int control= opciones_de_gestionar_tarj_combustible.registrar(uc);
                    reset_campos();
                    paneles_de_paneles.de_gestionar_info_laboratorio_añadir.this.setEnabled(true);
                    l.setVisible(false);
                    if(control==1){
                    SuccessAlert e = new SuccessAlert(new JFrame(), true);
            e.msj1.setText("¡Los datos del contrato fueron");
            e.msj2.setText("guardados exitosamente!.");
            e.msj3.setText("");
            e.setVisible(true);
                    }
                    
                    }catch(Exception e){
                        ErrorAlert error = new ErrorAlert(new JFrame(), true);
                        Logger.getLogger(opciones_de_gestionar_contrato.class.getName()).log(Level.SEVERE, null, e);
            error.msj1.setText(e.toString());
            error.msj2.setText("Por favor solucione el error antes de volver a intentarlo.");
            error.msj3.setText("En caso de no saber como corregir el error, por favor contacte con soporte técnico");
            error.preferredSize();
            error.pack();
            error.setVisible(true);
                    }
                }
            };
            Thread t1 = new Thread(runnable1);
            t1.start();
        }

    }//GEN-LAST:event_boton_guardar_tarjetaActionPerformed

    private void ping_tarjetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ping_tarjetaKeyReleased
        // TODO add your handling code here:
        if(ping_tarjeta.getText().length()>0){
            lbl_error_ping_tarjeta.setVisible(false);
        }
    }//GEN-LAST:event_ping_tarjetaKeyReleased

    private void ping_tarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ping_tarjetaKeyTyped
        // TODO add your handling code here:
        if(ping_tarjeta.getText().length()<4){
                char num = evt.getKeyChar();
        if ((num < '0' || num > '9')) {
            evt.consume();
            
        }
        }else{
            evt.consume();
        }
    }//GEN-LAST:event_ping_tarjetaKeyTyped

    private void numero_tarjeta_tarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_tarjeta_tarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero_tarjeta_tarjetaActionPerformed

    private void numero_chapa_tarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_chapa_tarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero_chapa_tarjetaActionPerformed

    private void numero_chapa_tarjetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numero_chapa_tarjetaKeyReleased
        // TODO add your handling code here:
        
        if(numero_chapa_tarjeta.getText().length()>0){
            lbl_error_numero_chapa.setVisible(false);
            char car = numero_chapa_tarjeta.getText().charAt(0);
            car=Character.toUpperCase(car);
            String txt=numero_chapa_tarjeta.getText().substring(1);
            numero_chapa_tarjeta.setText(String.valueOf(car)+txt);
        }
    }//GEN-LAST:event_numero_chapa_tarjetaKeyReleased

    private void numero_chapa_tarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numero_chapa_tarjetaKeyTyped
        // TODO add your handling code here:
            
        if (numero_chapa_tarjeta.getText().length() > 0 &&numero_chapa_tarjeta.getText().length() < 7) {
            char car = evt.getKeyChar();
            if (Character.isDigit(car)) {
                
            } else {
                evt.consume();
            }

        }else{
            if(numero_chapa_tarjeta.getText().length() < 7){
        char car = evt.getKeyChar();
        if ( Character.isLetter(car)) {
            
        } else {
            evt.consume();
        }
        }else{
                evt.consume();
            }
        }
    }//GEN-LAST:event_numero_chapa_tarjetaKeyTyped

    private void fecha_iasignacion_tarjetaAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_fecha_iasignacion_tarjetaAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha_iasignacion_tarjetaAncestorRemoved

    private String toma_fecha(JDateChooser fecha) {      
        String txt_fecha = null;
        if (fecha.getDate() != null) {
             String formato = fecha.getDateFormatString();
            Date date = fecha.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat(formato);
            txt_fecha=String.valueOf(sdf.format(date));
        }
        return txt_fecha;
    }                   
    
    private void reset_campos(){
        numero_tarjeta_tarjeta.setText("");
        numero_cant_litros_tarjeta.setText("");
        ping_tarjeta.setText("");
        numero_chapa_tarjeta.setText("");
        fecha_iasignacion_tarjeta.setDate(null);
        combo_tipo_combustible.setSelectedIndex(0);
        lbl_error_cant_litro_tarjeta.setVisible(false);
        lbl_error_numero_tarjeta.setVisible(false);
        lbl_error_fecha_asignacion_tarjeta.setVisible(false);
        lbl_error_tipo_combustible.setVisible(false);
        lbl_error_ping_tarjeta.setVisible(false);
        lbl_error_numero_chapa.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple boton_guardar_tarjeta;
    private org.bolivia.combo.SComboBox combo_tipo_combustible;
    private com.toedter.calendar.JDateChooser fecha_iasignacion_tarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_error_cant_litro_tarjeta;
    private javax.swing.JLabel lbl_error_fecha_asignacion_tarjeta;
    private javax.swing.JLabel lbl_error_numero_chapa;
    private javax.swing.JLabel lbl_error_numero_tarjeta;
    private javax.swing.JLabel lbl_error_ping_tarjeta;
    private javax.swing.JLabel lbl_error_tipo_combustible;
    public static rojeru_san.rsfield.RSTextMaterial numero_cant_litros_tarjeta;
    public static rojeru_san.rsfield.RSTextMaterial numero_chapa_tarjeta;
    public static rojeru_san.rsfield.RSTextMaterial numero_tarjeta_tarjeta;
    public static rojeru_san.rsfield.RSTextMaterial ping_tarjeta;
    // End of variables declaration//GEN-END:variables
}
