/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles_de_paneles;

import DAO.PdfDAO;
import Tabla.Tabla_PdfVO;
import VO.PdfVO;
import alertas.ErrorAlert;
import alertas.SuccessAlert;
import alertas.WarningAlert;
import esperas.Guardando_general;
import interaccion_bd.opciones_de_gestionar_contrato;
import java.awt.Event;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.InputMap;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import javax.swing.filechooser.FileNameExtensionFilter;
import static paneles_de_paneles.de_gestionar_contrato_añadir.numero_contrato;

/**
 *
 * @author RojeruSan
 */
public class de_gestionar_plano_añadir extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public de_gestionar_plano_añadir() {
        initComponents();
        lbl_error_nombre_plano.setVisible(false);
        lbl_error_pdf_plano.setVisible(false);
        deshabilitarPegar();
    }

     String  ruta_archivo="";
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre_plano = new rojeru_san.rsfield.RSTextMaterial();
        lbl_error_nombre_plano = new javax.swing.JLabel();
        boton_guardar_plano = new rojeru_san.RSButtonRiple();
        lb_foto = new javax.swing.JLabel();
        boton_busca_plano = new rojeru_san.RSButtonRiple();
        lbl_error_pdf_plano = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        nombre_plano.setForeground(new java.awt.Color(0, 0, 0));
        nombre_plano.setColorMaterial(new java.awt.Color(99, 70, 250));
        nombre_plano.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nombre_plano.setPlaceholder("Nombre del plano...");
        nombre_plano.setSelectionColor(new java.awt.Color(220, 23, 111));
        nombre_plano.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombre_planoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombre_planoKeyTyped(evt);
            }
        });

        lbl_error_nombre_plano.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_nombre_plano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_nombre_plano.setText("¡Debe ingresar un nombre de plano!");

        boton_guardar_plano.setBackground(new java.awt.Color(38, 86, 186));
        boton_guardar_plano.setText("Guardar Plano");
        boton_guardar_plano.setColorHover(new java.awt.Color(173, 187, 194));
        boton_guardar_plano.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_guardar_plano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardar_planoActionPerformed(evt);
            }
        });

        lb_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_planos/foto_plano.png"))); // NOI18N

        boton_busca_plano.setBackground(new java.awt.Color(38, 86, 186));
        boton_busca_plano.setText("Buscar Plano");
        boton_busca_plano.setColorHover(new java.awt.Color(173, 187, 194));
        boton_busca_plano.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_busca_plano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_busca_planoActionPerformed(evt);
            }
        });

        lbl_error_pdf_plano.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_pdf_plano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_pdf_plano.setText("¡Debe buscar un plano!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_guardar_plano, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbl_error_nombre_plano, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nombre_plano, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_busca_plano, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(lbl_error_pdf_plano)))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(nombre_plano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbl_error_nombre_plano, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(boton_guardar_plano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(boton_busca_plano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_error_pdf_plano, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombre_planoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_planoKeyReleased
        // TODO add your handling code here:
        if(nombre_plano.getText().length()>0){
            lbl_error_nombre_plano.setVisible(false);
        }
    }//GEN-LAST:event_nombre_planoKeyReleased

    private void nombre_planoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_planoKeyTyped
        // TODO add your handling code here:
        char letras = evt.getKeyChar();
        if ((letras < 'a' || letras > 'z') && (letras < 'A' | letras > 'Z')) {
            if ((letras != 'ñ') && (letras != 'Ñ') && (letras != 'á') && (letras != 'Á') && (letras != 'é') && (letras != 'É') && (letras != 'í')
                && (letras != 'Í') && (letras != 'ó') && (letras != 'Ó') && (letras != 'ú') && (letras != 'Ú') && (letras != ' ')) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_nombre_planoKeyTyped

    Tabla_PdfVO tpdf = new Tabla_PdfVO();
    private void boton_guardar_planoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardar_planoActionPerformed
       String sql="select * from planos where nombre_plano='"+nombre_plano.getText()+"'";
       String mje1="Ya existe un plano con ese nombre("+nombre_plano.getText()+")";
       String mje2="¿Desea guardarlo de todas farmas?";
       String mje3="La base de datos contendrá más de un plano con el mismo nombre";
        if (nombre_plano.getText().isEmpty()||boton_busca_plano.getText().equals("Buscar Plano")) {
               if(nombre_plano.getText().isEmpty()){
                lbl_error_nombre_plano.setVisible(true);
               }else if(boton_busca_plano.getText().equals("Buscar Plano")){
                lbl_error_pdf_plano.setVisible(true);
               }
        } else {
            if (interaccion_bd.opciones_de_gestionar_contrato.existe(nombre_plano.getText(), sql)) {
                WarningAlert a=new WarningAlert(new JFrame(), true);
                            a.msj1.setText(mje1);
                            a.msj2.setText(mje2);
                            a.msj3.setText(mje3);
                            a.setVisible(true);
                            if(a.hecho==false){
                            nombre_plano.requestFocus();
                            }else{
                                Runnable runnable1 = new Runnable() {
                public void run() {
                    Guardando_general l = new Guardando_general(new JFrame(), true);
                    l.setLocationRelativeTo(paneles_de_paneles.de_gestionar_plano_añadir.this);
                    l.setVisible(true);
                    try{
                    paneles_de_paneles.de_gestionar_plano_añadir.this.setEnabled(false);
                    accion_guardar();
                    paneles_de_paneles.de_gestionar_plano_añadir.this.setEnabled(true);
                    l.setVisible(false);
                        
                    }catch(Exception e){
                        Logger.getLogger(opciones_de_gestionar_contrato.class.getName()).log(Level.SEVERE, null, e);
                        opciones_de_gestionar_contrato.lanza_error(e);
                    }
                }
            };
            Thread t1 = new Thread(runnable1);
            t1.start();
                            }
                        }else{
            Runnable runnable1 = new Runnable() {
                public void run() {
                    Guardando_general l = new Guardando_general(new JFrame(), true);
                    l.setLocationRelativeTo(paneles_de_paneles.de_gestionar_plano_añadir.this);
                    l.setVisible(true);
                    try{
                    paneles_de_paneles.de_gestionar_plano_añadir.this.setEnabled(false);
                    accion_guardar();
                    paneles_de_paneles.de_gestionar_plano_añadir.this.setEnabled(true);
                    l.setVisible(false);
                        
                    }catch(Exception e){
                        ErrorAlert error = new ErrorAlert(new JFrame(), true);
                        Logger.getLogger(opciones_de_gestionar_contrato.class.getName()).log(Level.SEVERE, null, e);
            error.msj1.setText(e.toString());
            error.msj2.setText("Por favor solucione el error antes de volver a intentarlo.");
            error.msj3.setText("En caso de no saber como corregir el error, por favor contacte con soporte técnico");
            error.preferredSize();
            error.pack();
            error.setVisible(true);
                    }
                }
            };
            Thread t1 = new Thread(runnable1);
            t1.start();
        }
    }
    }//GEN-LAST:event_boton_guardar_planoActionPerformed

    public void accion_guardar(){
        try{
        String nombre = nombre_plano.getText();
        File ruta = new File(ruta_archivo);
        if (nombre.trim().length() != 0 && ruta_archivo.trim().length() != 0) {
            guardar_pdf(nombre, ruta);
         //   tpdf.visualizar_PdfVO(tabla);
            ruta_archivo = "";
            reset_campos();
            SuccessAlert e = new SuccessAlert(new JFrame(), true);
            e.msj1.setText("¡Los datos del plano fueron");
            e.msj2.setText("guardados exitosamente!.");
            e.msj3.setText("");
            e.setVisible(true);
        } 
        }catch(Exception ex){
            opciones_de_gestionar_contrato.lanza_error(ex);
        }
    }
    
    public void guardar_pdf( String nombre, File ruta) {
        PdfDAO pa = new PdfDAO();
        PdfVO po = new PdfVO();
        po.setNombrepdf(nombre);
        try {
            byte[] pdf = new byte[(int) ruta.length()];
            InputStream input = new FileInputStream(ruta);
            input.read(pdf);
            po.setArchivopdf(pdf);
        } catch (IOException ex) {
            po.setArchivopdf(null);
        }
        pa.Agregar_PdfVO(po);
    }
    
    private void boton_busca_planoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_busca_planoActionPerformed
        // TODO add your handling code here:
        try{
         JFileChooser j = new JFileChooser();
        FileNameExtensionFilter fi = new FileNameExtensionFilter("pdf", "pdf");
        j.setFileFilter(fi);
        int se = j.showOpenDialog(this);
        if (se == 0) {
            this.boton_busca_plano.setText("" + j.getSelectedFile().getName());
          ruta_archivo = j.getSelectedFile().getAbsolutePath();
          
          lb_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_planos/pdf2.png"))); 
          lbl_error_pdf_plano.setVisible(false);
        }  
        }catch(Exception ex){
            opciones_de_gestionar_contrato.lanza_error(ex);
        }
    }//GEN-LAST:event_boton_busca_planoActionPerformed

     private void deshabilitarPegar() {
        InputMap map2 = nombre_plano.getInputMap(nombre_plano.WHEN_FOCUSED);
        map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    }
               
    private void reset_campos(){
        nombre_plano.setText("");
        boton_busca_plano.setText("Buscar Plano");
        lb_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_planos/foto_plano.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple boton_busca_plano;
    private rojeru_san.RSButtonRiple boton_guardar_plano;
    private javax.swing.JLabel lb_foto;
    private javax.swing.JLabel lbl_error_nombre_plano;
    private javax.swing.JLabel lbl_error_pdf_plano;
    public static rojeru_san.rsfield.RSTextMaterial nombre_plano;
    // End of variables declaration//GEN-END:variables
}
