/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles_de_paneles;

import DAO.PdfDAO;
import DAO.PdfDAO_ficha_costo;
import DAO.PdfDAO_prep_tecnica;
import Tabla.Tabla_PdfVO;
import Tabla.Tabla_PdfVO_prep_tecnica;
import VO.PdfVO;
import VO.PdfVO_ficha_costo;
import VO.PdfVO_prep_tecnica;
import alertas.ErrorAlert;
import alertas.SuccessAlert;
import alertas.WarningAlert;
import esperas.Guardando_general;
import interaccion_bd.opciones_de_gestionar_contrato;
import java.awt.Event;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author RojeruSan
 */
public class de_gestionar_ficha_costo_añadir extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public de_gestionar_ficha_costo_añadir() {
        initComponents();
        lbl_error_nombre_ficha_costo.setVisible(false);
        lbl_error_pdf_ficha_costo.setVisible(false);
        deshabilitarPegar();
    }

    
    
     String  ruta_archivo="";
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre_ficha_costo = new rojeru_san.rsfield.RSTextMaterial();
        lbl_error_nombre_ficha_costo = new javax.swing.JLabel();
        boton_guardar_ficha_costo = new rojeru_san.RSButtonRiple();
        lb_foto = new javax.swing.JLabel();
        boton_busca_ficha_costo = new rojeru_san.RSButtonRiple();
        lbl_error_pdf_ficha_costo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        nombre_ficha_costo.setForeground(new java.awt.Color(0, 0, 0));
        nombre_ficha_costo.setColorMaterial(new java.awt.Color(99, 70, 250));
        nombre_ficha_costo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nombre_ficha_costo.setPlaceholder("Nombre de la ficha de costo...");
        nombre_ficha_costo.setSelectionColor(new java.awt.Color(220, 23, 111));
        nombre_ficha_costo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombre_ficha_costoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombre_ficha_costoKeyTyped(evt);
            }
        });

        lbl_error_nombre_ficha_costo.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_nombre_ficha_costo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_nombre_ficha_costo.setText("¡Debe ingresar un nombre de ficha de costo!");

        boton_guardar_ficha_costo.setBackground(new java.awt.Color(38, 86, 186));
        boton_guardar_ficha_costo.setText("Guardar Ficha de Costo");
        boton_guardar_ficha_costo.setColorHover(new java.awt.Color(173, 187, 194));
        boton_guardar_ficha_costo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_guardar_ficha_costo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardar_ficha_costoActionPerformed(evt);
            }
        });

        lb_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_ficha_costo/ficha_costo.png"))); // NOI18N

        boton_busca_ficha_costo.setBackground(new java.awt.Color(38, 86, 186));
        boton_busca_ficha_costo.setText("Buscar Ficha de Costo");
        boton_busca_ficha_costo.setColorHover(new java.awt.Color(173, 187, 194));
        boton_busca_ficha_costo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_busca_ficha_costo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_busca_ficha_costoActionPerformed(evt);
            }
        });

        lbl_error_pdf_ficha_costo.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_pdf_ficha_costo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_pdf_ficha_costo.setText("¡Debe buscar una ficha de costo!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_error_nombre_ficha_costo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombre_ficha_costo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton_guardar_ficha_costo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_busca_ficha_costo, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(lbl_error_pdf_ficha_costo)))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(nombre_ficha_costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbl_error_nombre_ficha_costo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(boton_guardar_ficha_costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(boton_busca_ficha_costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_error_pdf_ficha_costo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombre_ficha_costoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_ficha_costoKeyReleased
        // TODO add your handling code here:
        if(nombre_ficha_costo.getText().length()>0){
            lbl_error_nombre_ficha_costo.setVisible(false);
        }
    }//GEN-LAST:event_nombre_ficha_costoKeyReleased

    private void nombre_ficha_costoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_ficha_costoKeyTyped
        // TODO add your handling code here:
        char letras = evt.getKeyChar();
        if ((letras < 'a' || letras > 'z') && (letras < 'A' | letras > 'Z')) {
            if ((letras != 'ñ') && (letras != 'Ñ') && (letras != 'á') && (letras != 'Á') && (letras != 'é') && (letras != 'É') && (letras != 'í')
                && (letras != 'Í') && (letras != 'ó') && (letras != 'Ó') && (letras != 'ú') && (letras != 'Ú') && (letras != ' ')) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_nombre_ficha_costoKeyTyped

    Tabla_PdfVO_prep_tecnica tpdf = new Tabla_PdfVO_prep_tecnica();
    private void boton_guardar_ficha_costoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardar_ficha_costoActionPerformed
       String sql="select * from ficha_costo where nombre_ficha='"+nombre_ficha_costo.getText()+"'";
       String mje1="Ya existe una ficha de costo con ese nombre("+nombre_ficha_costo.getText()+")";
       String mje2="¿Desea guardarlo de todas farmas?";
       String mje3="La base de datos contendrá más de una ficha de costo con el mismo nombre";
        if (nombre_ficha_costo.getText().isEmpty()||boton_busca_ficha_costo.getText().equals("Buscar Ficha de Costo")) {
               if(nombre_ficha_costo.getText().isEmpty()){
                lbl_error_nombre_ficha_costo.setVisible(true);
               }else if(boton_busca_ficha_costo.getText().equals("Buscar Ficha de Costo")){
                lbl_error_pdf_ficha_costo.setVisible(true);
               }
        } else {
            if (interaccion_bd.opciones_de_gestionar_contrato.existe(nombre_ficha_costo.getText(), sql)) {
                WarningAlert a=new WarningAlert(new JFrame(), true);
                            a.msj1.setText(mje1);
                            a.msj2.setText(mje2);
                            a.msj3.setText(mje3);
                            a.setVisible(true);
                            if(a.hecho==false){
                            nombre_ficha_costo.requestFocus();
                            }else{
                                Runnable runnable1 = new Runnable() {
                public void run() {
                    Guardando_general l = new Guardando_general(new JFrame(), true);
                    l.setLocationRelativeTo(paneles_de_paneles.de_gestionar_ficha_costo_añadir.this);
                    l.setVisible(true);
                    try{
                    paneles_de_paneles.de_gestionar_ficha_costo_añadir.this.setEnabled(false);
                    accion_guardar();
                    paneles_de_paneles.de_gestionar_ficha_costo_añadir.this.setEnabled(true);
                    l.setVisible(false);
                        
                    }catch(Exception e){
                        Logger.getLogger(opciones_de_gestionar_contrato.class.getName()).log(Level.SEVERE, null, e);
                        opciones_de_gestionar_contrato.lanza_error(e);
                    }
                }
            };
            Thread t1 = new Thread(runnable1);
            t1.start();
                            }
                        }else{
            Runnable runnable1 = new Runnable() {
                public void run() {
                    Guardando_general l = new Guardando_general(new JFrame(), true);
                    l.setLocationRelativeTo(paneles_de_paneles.de_gestionar_ficha_costo_añadir.this);
                    l.setVisible(true);
                    try{
                    paneles_de_paneles.de_gestionar_ficha_costo_añadir.this.setEnabled(false);
                    accion_guardar();
                    paneles_de_paneles.de_gestionar_ficha_costo_añadir.this.setEnabled(true);
                    l.setVisible(false);
                        
                    }catch(Exception e){
                        Logger.getLogger(opciones_de_gestionar_contrato.class.getName()).log(Level.SEVERE, null, e);
                        opciones_de_gestionar_contrato.lanza_error(e);
                    }
                }
            };
            Thread t1 = new Thread(runnable1);
            t1.start();
        }
    }
    }//GEN-LAST:event_boton_guardar_ficha_costoActionPerformed

    public void accion_guardar(){
        try{
        String nombre = nombre_ficha_costo.getText();
        File ruta = new File(ruta_archivo);
        if (nombre.trim().length() != 0 && ruta_archivo.trim().length() != 0) {
            guardar_pdf(nombre, ruta);
         //   tpdf.visualizar_PdfVO(tabla);
            ruta_archivo = "";
            reset_campos();
            SuccessAlert e = new SuccessAlert(new JFrame(), true);
            e.msj1.setText("¡Los datos de la ficha de costo fueron");
            e.msj2.setText("guardados exitosamente!.");
            e.msj3.setText("");
            e.setVisible(true);
        } 
        }catch(Exception ex){
            opciones_de_gestionar_contrato.lanza_error(ex);
        }
    }
    
    public void guardar_pdf( String nombre, File ruta) {
        PdfDAO_ficha_costo pa = new PdfDAO_ficha_costo();
        PdfVO_ficha_costo po = new PdfVO_ficha_costo();
        po.setNombrepdf(nombre);
        try {
            byte[] pdf = new byte[(int) ruta.length()];
            InputStream input = new FileInputStream(ruta);
            input.read(pdf);
            po.setArchivopdf(pdf);
        } catch (IOException ex) {
            po.setArchivopdf(null);
        }
        pa.Agregar_PdfVO(po);
    }
    
    private void boton_busca_ficha_costoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_busca_ficha_costoActionPerformed
        // TODO add your handling code here:
        try{
         JFileChooser j = new JFileChooser();
        FileNameExtensionFilter fi = new FileNameExtensionFilter("pdf", "pdf");
        j.setFileFilter(fi);
        int se = j.showOpenDialog(this);
        if (se == 0) {
            this.boton_busca_ficha_costo.setText("" + j.getSelectedFile().getName());
          ruta_archivo = j.getSelectedFile().getAbsolutePath();
          
          lb_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_planos/pdf2.png"))); 
          lbl_error_pdf_ficha_costo.setVisible(false);
        }  
        }catch(Exception ex){
            opciones_de_gestionar_contrato.lanza_error(ex);
        }
    }//GEN-LAST:event_boton_busca_ficha_costoActionPerformed

     private void deshabilitarPegar() {
        InputMap map2 = nombre_ficha_costo.getInputMap(nombre_ficha_costo.WHEN_FOCUSED);
        map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    }
               
    private void reset_campos(){
        nombre_ficha_costo.setText("");
        boton_busca_ficha_costo.setText("Buscar Plano");
        lb_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_ficha_costo/ficha_costo.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple boton_busca_ficha_costo;
    private rojeru_san.RSButtonRiple boton_guardar_ficha_costo;
    private javax.swing.JLabel lb_foto;
    private javax.swing.JLabel lbl_error_nombre_ficha_costo;
    private javax.swing.JLabel lbl_error_pdf_ficha_costo;
    public static rojeru_san.rsfield.RSTextMaterial nombre_ficha_costo;
    // End of variables declaration//GEN-END:variables
}
