/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles_de_paneles;

import alertas.SuccessAlert;
import esperas.Guardando_general;
import interaccion_bd.consultas_de_gestionar_recursos_x_programa;
import interaccion_bd.opciones_de_gestionar_contrato;
import interaccion_bd.opciones_de_gestionar_info_lab;
import interaccion_bd.opciones_de_gestionar_prod_programa;
import interaccion_bd.opciones_de_gestionar_recursos_x_programa;
import java.awt.Event;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.Date;
import javax.swing.InputMap;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author RojeruSan
 */
public class de_gestionar_info_laboratorio_añadir extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public de_gestionar_info_laboratorio_añadir() {
        initComponents();
        
        lbl_error_asent_add.setVisible(false);
        lbl_error_vol_m3_add.setVisible(false);
        lbl_error_fecha_info_lab_add.setVisible(false);
        lbl_error_lm_add.setVisible(false);
        lbl_error_num_materiales_add.setVisible(false);
        lbl_error_pm_add.setVisible(false);
        lbl_error_x1_28dias_add.setEnabled(false);
        lbl_error_x1_add.setEnabled(false);
        lbl_error_x2_28dias_add.setEnabled(false);
        lbl_error_x2_add.setEnabled(false);
        lbl_error_x3_28dias_add.setEnabled(false);
        lbl_error_x3_add.setEnabled(false);
        deshabilitarPegar();
        opciones_de_gestionar_info_lab.get_combos(combo_lm, combo_pm);
        //################### detectar cambios en los combobox ######################3
        combo_lm.addItemListener(new ItemListener() {
           public void itemStateChanged(ItemEvent arg0) {
               //Do Something
              lbl_error_lm_add.setVisible(false);
           }
           
            public void itemStateChangedd(ItemEvent e) {
             //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
       });
        
        combo_pm.addItemListener(new ItemListener() {
           public void itemStateChanged(ItemEvent arg0) {
               //Do Something
              lbl_error_pm_add.setVisible(false);
           }
           
            public void itemStateChangedd(ItemEvent e) {
             //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
       });
        // ##########################################################################
    
        
        //  detectar cambio en jdateChoser (fecha de inicio en agregar contrato)
        fecha_info_lab_add.getDateEditor().addPropertyChangeListener(
                new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent e) {
                if ("date".equals(e.getPropertyName())) {
                    System.out.println(e.getPropertyName()
                            + ": " + (Date) e.getNewValue());
                    if(fecha_info_lab_add.getDate()==null){
                       lbl_error_fecha_info_lab_add.setVisible(true);
                    }
                }else{
                    lbl_error_fecha_info_lab_add.setVisible(false);
                }
            }
        });
        this.add(fecha_info_lab_add);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        boton_guardar_recursos_x_programa_add = new rojeru_san.RSButtonRiple();
        num_materiales_add = new rojeru_san.rsfield.RSTextMaterial();
        lbl_error_num_materiales_add = new javax.swing.JLabel();
        vol_m3_add = new rojeru_san.rsfield.RSTextMaterial();
        fecha_info_lab_add = new com.toedter.calendar.JDateChooser();
        asent_add = new rojeru_san.rsfield.RSTextMaterial();
        x2_add = new rojeru_san.rsfield.RSTextMaterial();
        x1_add = new rojeru_san.rsfield.RSTextMaterial();
        x3_add = new rojeru_san.rsfield.RSTextMaterial();
        combo_lm = new org.bolivia.combo.SComboBox();
        check_prefabricados1 = new check_de_android.Switch();
        check_prefabricados2 = new check_de_android.Switch();
        combo_pm = new org.bolivia.combo.SComboBox();
        check_prefabricados3 = new check_de_android.Switch();
        x1_28dias_add = new rojeru_san.rsfield.RSTextMaterial();
        x2_28dias_add = new rojeru_san.rsfield.RSTextMaterial();
        x3_28dias_add = new rojeru_san.rsfield.RSTextMaterial();
        lbl_error_lm_add = new javax.swing.JLabel();
        lbl_error_pm_add = new javax.swing.JLabel();
        lbl_error_fecha_info_lab_add = new javax.swing.JLabel();
        lbl_error_x1_add = new javax.swing.JLabel();
        lbl_error_x2_add = new javax.swing.JLabel();
        lbl_error_x3_add = new javax.swing.JLabel();
        lbl_error_x3_28dias_add = new javax.swing.JLabel();
        lbl_error_vol_m3_add = new javax.swing.JLabel();
        lbl_error_asent_add = new javax.swing.JLabel();
        lbl_error_x1_28dias_add = new javax.swing.JLabel();
        lbl_error_x2_28dias_add = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_info_lab/info_lab.png"))); // NOI18N

        boton_guardar_recursos_x_programa_add.setBackground(new java.awt.Color(38, 86, 186));
        boton_guardar_recursos_x_programa_add.setText("Guardar Cambios");
        boton_guardar_recursos_x_programa_add.setColorHover(new java.awt.Color(173, 187, 194));
        boton_guardar_recursos_x_programa_add.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_guardar_recursos_x_programa_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardar_recursos_x_programa_addActionPerformed(evt);
            }
        });

        num_materiales_add.setForeground(new java.awt.Color(0, 0, 0));
        num_materiales_add.setColorMaterial(new java.awt.Color(99, 70, 250));
        num_materiales_add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num_materiales_add.setPlaceholder("Número de materiales...");
        num_materiales_add.setSelectionColor(new java.awt.Color(220, 23, 111));
        num_materiales_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_materiales_addActionPerformed(evt);
            }
        });
        num_materiales_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                num_materiales_addKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                num_materiales_addKeyTyped(evt);
            }
        });

        lbl_error_num_materiales_add.setForeground(new java.awt.Color(255, 0, 0));
        lbl_error_num_materiales_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_num_materiales_add.setText("¡Debe ingresar un número!");

        vol_m3_add.setForeground(new java.awt.Color(0, 0, 0));
        vol_m3_add.setColorMaterial(new java.awt.Color(99, 70, 250));
        vol_m3_add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        vol_m3_add.setPlaceholder("Volumen (m3)...");
        vol_m3_add.setSelectionColor(new java.awt.Color(220, 23, 111));
        vol_m3_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vol_m3_addKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vol_m3_addKeyTyped(evt);
            }
        });

        fecha_info_lab_add.setDateFormatString("dd/MM/yyyy");
        fecha_info_lab_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fecha_info_lab_add.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                fecha_info_lab_addAncestorRemoved(evt);
            }
        });

        asent_add.setForeground(new java.awt.Color(0, 0, 0));
        asent_add.setColorMaterial(new java.awt.Color(99, 70, 250));
        asent_add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        asent_add.setPlaceholder("Asent. (cm)...");
        asent_add.setSelectionColor(new java.awt.Color(220, 23, 111));
        asent_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                asent_addKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                asent_addKeyTyped(evt);
            }
        });

        x2_add.setForeground(new java.awt.Color(0, 0, 0));
        x2_add.setColorMaterial(new java.awt.Color(99, 70, 250));
        x2_add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        x2_add.setPlaceholder("x2 (3 días)...");
        x2_add.setSelectionColor(new java.awt.Color(220, 23, 111));
        x2_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                x2_addKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                x2_addKeyTyped(evt);
            }
        });

        x1_add.setForeground(new java.awt.Color(0, 0, 0));
        x1_add.setColorMaterial(new java.awt.Color(99, 70, 250));
        x1_add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        x1_add.setPlaceholder("X1 (3 días)...");
        x1_add.setSelectionColor(new java.awt.Color(220, 23, 111));
        x1_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                x1_addKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                x1_addKeyTyped(evt);
            }
        });

        x3_add.setForeground(new java.awt.Color(0, 0, 0));
        x3_add.setColorMaterial(new java.awt.Color(99, 70, 250));
        x3_add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        x3_add.setPlaceholder("X3 (3 días)...");
        x3_add.setSelectionColor(new java.awt.Color(220, 23, 111));
        x3_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                x3_addKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                x3_addKeyTyped(evt);
            }
        });

        combo_lm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MATERIALES (LM)" }));
        combo_lm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_lmActionPerformed(evt);
            }
        });

        check_prefabricados1.setToolTipText("Hacer o deshacer editable");
        check_prefabricados1.setBackgroundColor(new java.awt.Color(38, 86, 186));
        check_prefabricados1.setOnOff(false);
        check_prefabricados1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check_prefabricados1MouseClicked(evt);
            }
        });

        check_prefabricados2.setToolTipText("Hacer o deshacer editable");
        check_prefabricados2.setBackgroundColor(new java.awt.Color(38, 86, 186));
        check_prefabricados2.setOnOff(false);
        check_prefabricados2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check_prefabricados2MouseClicked(evt);
            }
        });

        combo_pm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MATERIALES (PM)" }));
        combo_pm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_pmActionPerformed(evt);
            }
        });

        check_prefabricados3.setToolTipText("Unir materiales");
        check_prefabricados3.setBackgroundColor(new java.awt.Color(38, 86, 186));
        check_prefabricados3.setOnOff(false);
        check_prefabricados3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check_prefabricados3MouseClicked(evt);
            }
        });

        x1_28dias_add.setForeground(new java.awt.Color(0, 0, 0));
        x1_28dias_add.setColorMaterial(new java.awt.Color(99, 70, 250));
        x1_28dias_add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        x1_28dias_add.setPlaceholder("X1 (28 días)...");
        x1_28dias_add.setSelectionColor(new java.awt.Color(220, 23, 111));
        x1_28dias_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                x1_28dias_addKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                x1_28dias_addKeyTyped(evt);
            }
        });

        x2_28dias_add.setForeground(new java.awt.Color(0, 0, 0));
        x2_28dias_add.setColorMaterial(new java.awt.Color(99, 70, 250));
        x2_28dias_add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        x2_28dias_add.setPlaceholder("x2 (28 días)...");
        x2_28dias_add.setSelectionColor(new java.awt.Color(220, 23, 111));
        x2_28dias_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                x2_28dias_addKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                x2_28dias_addKeyTyped(evt);
            }
        });

        x3_28dias_add.setForeground(new java.awt.Color(0, 0, 0));
        x3_28dias_add.setColorMaterial(new java.awt.Color(99, 70, 250));
        x3_28dias_add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        x3_28dias_add.setPlaceholder("X3 (28 días)...");
        x3_28dias_add.setSelectionColor(new java.awt.Color(220, 23, 111));
        x3_28dias_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                x3_28dias_addKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                x3_28dias_addKeyTyped(evt);
            }
        });

        lbl_error_lm_add.setForeground(new java.awt.Color(255, 0, 0));
        lbl_error_lm_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_lm_add.setText("¡Debe ingresar un material!");

        lbl_error_pm_add.setForeground(new java.awt.Color(255, 0, 0));
        lbl_error_pm_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_pm_add.setText("¡Debe ingresar un material!");

        lbl_error_fecha_info_lab_add.setForeground(new java.awt.Color(255, 0, 0));
        lbl_error_fecha_info_lab_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_fecha_info_lab_add.setText("¡Debe ingresar una fecha!");

        lbl_error_x1_add.setForeground(new java.awt.Color(255, 0, 0));
        lbl_error_x1_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_x1_add.setText("¡Debe ingresar un número!");

        lbl_error_x2_add.setForeground(new java.awt.Color(255, 0, 0));
        lbl_error_x2_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_x2_add.setText("¡Debe ingresar un número!");

        lbl_error_x3_add.setForeground(new java.awt.Color(255, 0, 0));
        lbl_error_x3_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_x3_add.setText("¡Debe ingresar un número!");

        lbl_error_x3_28dias_add.setForeground(new java.awt.Color(255, 0, 0));
        lbl_error_x3_28dias_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_x3_28dias_add.setText("¡Debe ingresar un número!");

        lbl_error_vol_m3_add.setForeground(new java.awt.Color(255, 0, 0));
        lbl_error_vol_m3_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_vol_m3_add.setText("¡Debe ingresar un número!");

        lbl_error_asent_add.setForeground(new java.awt.Color(255, 0, 0));
        lbl_error_asent_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_asent_add.setText("¡Debe ingresar un número!");

        lbl_error_x1_28dias_add.setForeground(new java.awt.Color(255, 0, 0));
        lbl_error_x1_28dias_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_x1_28dias_add.setText("¡Debe ingresar un número!");

        lbl_error_x2_28dias_add.setForeground(new java.awt.Color(255, 0, 0));
        lbl_error_x2_28dias_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_x2_28dias_add.setText("¡Debe ingresar un número!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(x1_28dias_add, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(x2_28dias_add, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_error_vol_m3_add)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(asent_add, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(vol_m3_add, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(check_prefabricados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(combo_lm, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addComponent(lbl_error_lm_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbl_error_asent_add)
                            .addComponent(lbl_error_x1_28dias_add)
                            .addComponent(lbl_error_x2_28dias_add))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(check_prefabricados3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(x1_add, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(combo_pm, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_prefabricados2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(x3_add, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbl_error_num_materiales_add, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(num_materiales_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fecha_info_lab_add, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_error_fecha_info_lab_add, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(x2_add, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x3_28dias_add, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_error_pm_add, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_error_x1_add)
                    .addComponent(lbl_error_x2_add)
                    .addComponent(lbl_error_x3_add)
                    .addComponent(lbl_error_x3_28dias_add))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(boton_guardar_recursos_x_programa_add, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(num_materiales_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbl_error_num_materiales_add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(fecha_info_lab_add, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_error_fecha_info_lab_add)))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vol_m3_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x1_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_error_x1_add)
                    .addComponent(lbl_error_vol_m3_add))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asent_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x2_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_error_asent_add)
                    .addComponent(lbl_error_x2_add))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(x1_28dias_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(x3_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_error_x3_add)
                    .addComponent(lbl_error_x1_28dias_add))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(x2_28dias_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbl_error_x2_28dias_add))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(x3_28dias_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbl_error_x3_28dias_add)))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_lm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(check_prefabricados1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_pm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(check_prefabricados2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_error_lm_add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_error_pm_add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(check_prefabricados3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(boton_guardar_recursos_x_programa_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void boton_guardar_recursos_x_programa_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardar_recursos_x_programa_addActionPerformed
//        String sql_elemento="select * from materia_prima where `elem__materia_prima`='"+combo_prefabricados_re_add.getSelectedItem().toString()+"'";
//        String sql_programa="SELECT * FROM `contrato` WHERE  `nombre_contrato`='"+combo_programas_re_add.getSelectedItem().toString()+"'";
//        String sql="select * from recursos_x_programa where codigo_re='"+num_materiales_add.getText()+"'";
//        String mje1="El código de recursos por programa que intenta registrar ya existe";
//        String mje2="Por favor introduzca un código distinto de recurso";
//        if (combo_prefabricados_re_add.getSelectedIndex()==0||
//                cantidad_re_add.getText().isEmpty()||combo_programas_re_add.getSelectedIndex()==0||factura_re_add.getText().isEmpty()||
//                carta_porte_re_add.getText().isEmpty()||opciones_de_gestionar_prod_programa.existe(sql_elemento) == false||opciones_de_gestionar_prod_programa.existe(sql_programa) == false) {
//            if(combo_prefabricados_re_add.getSelectedIndex()==0){
//                combo_prefabricados_re_add.requestFocus();
//                lbl_error_descripcion_re_add.setVisible(true);
//            }else if(cantidad_re_add.getText().isEmpty()){
//                cantidad_re_add.requestFocus();
//                lbl_error_cant_re_add.setVisible(true);
//            }else if(combo_programas_re_add.getSelectedIndex()==0){
//                combo_programas_re_add.requestFocus();
//                lbl_error_programa_re_add.setVisible(true);
//            }else if(factura_re_add.getText().isEmpty()){
//                factura_re_add.requestFocus();
//                lbl_error_factura_re_add.setVisible(true);
//            }else if(carta_porte_re_add.getText().isEmpty()){
//                carta_porte_re_add.requestFocus();
//                lbl_error_carta_porte_add.setVisible(true);
//            }else if(opciones_de_gestionar_prod_programa.existe(sql_elemento) == false){
//            opciones_de_gestionar_contrato.lanza_error_variable_sin_ex("El elemento descrito no se encuentra en la base de datos.",
//                "Por favor, elija uno de los existentes en nuestra base de datos.",
//                "");
//            combo_prefabricados_re_add.requestFocus();
//            }else if(opciones_de_gestionar_prod_programa.existe(sql_programa) == false){
//            opciones_de_gestionar_contrato.lanza_error_variable_sin_ex("El programa descrito no se encuentra en la base de datos.",
//                "Por favor, si es real, regístrelo antes de volver a intentarlo.",
//                "De lo contrario seleccione uno existente en nuestra base de datos");
//            combo_programas_re_add.requestFocus();
//            }        } else {
//
//                if (interaccion_bd.opciones_de_gestionar_contrato.existe(num_materiales_add.getText(), sql)) {
//                    opciones_de_gestionar_contrato.lanza_error_variable_sin_ex("",mje1,mje2);
//                    cantidad_re_add.requestFocus();
//                }else{
//                    Guardando_general l = new Guardando_general(new JFrame(), true);
//                    consultas_de_gestionar_recursos_x_programa uc=new consultas_de_gestionar_recursos_x_programa();
//                    l.setLocationRelativeTo(paneles_de_paneles.de_gestionar_info_laboratorio_añadir.this);
//                    l.setVisible(true);
//                    paneles_de_paneles.de_gestionar_info_laboratorio_añadir.this.setEnabled(false);
//                    uc.setCodigo(num_materiales_add.getText());
//                uc.setDescripcion(combo_prefabricados_re_add.getSelectedItem().toString());
//                uc.setUm(um_re_add.getText());
//                uc.setCant(cantidad_re_add.getText());
//                uc.setPrograma_pertenece(combo_programas_re_add.getSelectedItem().toString());
//                uc.setFactura(factura_re_add.getText());
//                uc.setCarta_porte(carta_porte_re_add.getText());
//                    int control= opciones_de_gestionar_recursos_x_programa.registrar(uc);
//                    paneles_de_paneles.de_gestionar_info_laboratorio_añadir.this.setEnabled(true);
//                    l.setVisible(false);
//                    if(control==1){
//                        reset_campos();
//                        opciones_de_gestionar_recursos_x_programa.setListar("");
//                        SuccessAlert e = new SuccessAlert(new JFrame(), true);
//                        e.msj1.setText("¡Los datos del recurso fueron");
//                        e.msj2.setText("guardados exitosamente!.");
//                        e.msj3.setText("");
//                        e.setVisible(true);
//                    }
//                }
//            
//        }
    }//GEN-LAST:event_boton_guardar_recursos_x_programa_addActionPerformed
    
    
    
    private void num_materiales_addKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_num_materiales_addKeyTyped
        // TODO add your handling code here:
         if(num_materiales_add.getText().length()<10){
        char num = evt.getKeyChar();
        if ((num < '0' || num > '9')) {
            evt.consume();
        }
        }else{
             evt.consume();
        }
    }//GEN-LAST:event_num_materiales_addKeyTyped

    private void num_materiales_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_materiales_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_materiales_addActionPerformed

    private void vol_m3_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vol_m3_addKeyReleased
        // TODO add your handling code here:
        if(vol_m3_add.getText().length()>0){
            lbl_error_vol_m3_add.setVisible(false);
        }
    }//GEN-LAST:event_vol_m3_addKeyReleased

    
//    int control=0;
    private void vol_m3_addKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vol_m3_addKeyTyped
        // TODO add your handling code here:
        int pto=0;
    int lugares=0;
        char caracter = evt.getKeyChar();
        if(caracter=='.'){
            pto++;
        }
        if( pto>=2){
            pto=2;
        }
        if( lugares>=3){
            lugares--;
        }

        if(caracter == KeyEvent.VK_BACK_SPACE){
            if( pto>=0){
                lugares--;
            }

            if(!vol_m3_add.getText().contains(".")){
                pto=0;
            }
            if( pto==0){
                lugares=0;
            }
        }
        if (vol_m3_add.getText().length() <1 ) {
            char car = evt.getKeyChar();
            if (car!='.' && Character.isDigit(car)) {
                // escribe
            } else {
                evt.consume();  // desecha
            }

        }else{
            if(vol_m3_add.getText().length()<10){
                char num = evt.getKeyChar();
                if (Character.isDigit(num)||num=='.') {
                    if(num=='.'&&pto<2){
                        // escribe
                    }else{
                        if(pto!=0&&num!='.'){
                            lugares++;
                        }
                        if(lugares<3 && num!='.'){
                            // escribe
                        }else{
                            evt.consume();
                        }
                    }
                }else{
                    evt.consume();
                }
            }else{
                evt.consume();
            }
        }

    }//GEN-LAST:event_vol_m3_addKeyTyped

    private void fecha_info_lab_addAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_fecha_info_lab_addAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha_info_lab_addAncestorRemoved

    private void asent_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_asent_addKeyReleased
        // TODO add your handling code here:
        if(asent_add.getText().length()>0){
            lbl_error_asent_add.setVisible(false);
        }
    }//GEN-LAST:event_asent_addKeyReleased

    private void asent_addKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_asent_addKeyTyped
        // TODO add your handling code here:
         int pto=0;
    int lugares=0;
        char caracter = evt.getKeyChar();
        if(caracter=='.'){
            pto++;
        }
        if( pto>=2){
            pto=2;
        }
        if( lugares>=3){
            lugares--;
        }

        if(caracter == KeyEvent.VK_BACK_SPACE){
            if( pto>=0){
                lugares--;
            }

            if(!asent_add.getText().contains(".")){
                pto=0;
            }
            if( pto==0){
                lugares=0;
            }
        }
        if (asent_add.getText().length() <1 ) {
            char car = evt.getKeyChar();
            if (car!='.' && Character.isDigit(car)) {
                // escribe
            } else {
                evt.consume();  // desecha
            }

        }else{
            if(asent_add.getText().length()<10){
                char num = evt.getKeyChar();
                if (Character.isDigit(num)||num=='.') {
                    if(num=='.'&&pto<2){
                        // escribe
                    }else{
                        if(pto!=0&&num!='.'){
                            lugares++;
                        }
                        if(lugares<3 && num!='.'){
                            // escribe
                        }else{
                            evt.consume();
                        }
                    }
                }else{
                    evt.consume();
                }
            }else{
                evt.consume();
            }
        }
    }//GEN-LAST:event_asent_addKeyTyped

    private void x2_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_x2_addKeyReleased
        // TODO add your handling code here:
        if(x2_add.getText().length()>0){
            lbl_error_x2_add.setVisible(false);
        }
    }//GEN-LAST:event_x2_addKeyReleased

    private void x2_addKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_x2_addKeyTyped
        // TODO add your handling code here:
        int pto=0;
    int lugares=0;
        char caracter = evt.getKeyChar();
        if(caracter=='.'){
            pto++;
        }
        if( pto>=2){
            pto=2;
        }
        if( lugares>=3){
            lugares--;
        }

        if(caracter == KeyEvent.VK_BACK_SPACE){
            if( pto>=0){
                lugares--;
            }

            if(!x2_add.getText().contains(".")){
                pto=0;
            }
            if( pto==0){
                lugares=0;
            }
        }
        if (x2_add.getText().length() <1 ) {
            char car = evt.getKeyChar();
            if (car!='.' && Character.isDigit(car)) {
                // escribe
            } else {
                evt.consume();  // desecha
            }

        }else{
            if(x2_add.getText().length()<10){
                char num = evt.getKeyChar();
                if (Character.isDigit(num)||num=='.') {
                    if(num=='.'&&pto<2){
                        // escribe
                    }else{
                        if(pto!=0&&num!='.'){
                            lugares++;
                        }
                        if(lugares<3 && num!='.'){
                            // escribe
                        }else{
                            evt.consume();
                        }
                    }
                }else{
                    evt.consume();
                }
            }else{
                evt.consume();
            }
        }
    }//GEN-LAST:event_x2_addKeyTyped

    private void x1_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_x1_addKeyReleased
        // TODO add your handling code here:
         if(x1_add.getText().length()>0){
            lbl_error_x1_add.setVisible(false);
        }
    }//GEN-LAST:event_x1_addKeyReleased

    private void x1_addKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_x1_addKeyTyped
        // TODO add your handling code here:
        int pto=0;
    int lugares=0;
        char caracter = evt.getKeyChar();
        if(caracter=='.'){
            pto++;
        }
        if( pto>=2){
            pto=2;
        }
        if( lugares>=3){
            lugares--;
        }

        if(caracter == KeyEvent.VK_BACK_SPACE){
            if( pto>=0){
                lugares--;
            }

            if(!x1_add.getText().contains(".")){
                pto=0;
            }
            if( pto==0){
                lugares=0;
            }
        }
        if (x1_add.getText().length() <1 ) {
            char car = evt.getKeyChar();
            if (car!='.' && Character.isDigit(car)) {
                // escribe
            } else {
                evt.consume();  // desecha
            }

        }else{
            if(x1_add.getText().length()<10){
                char num = evt.getKeyChar();
                if (Character.isDigit(num)||num=='.') {
                    if(num=='.'&&pto<2){
                        // escribe
                    }else{
                        if(pto!=0&&num!='.'){
                            lugares++;
                        }
                        if(lugares<3 && num!='.'){
                            // escribe
                        }else{
                            evt.consume();
                        }
                    }
                }else{
                    evt.consume();
                }
            }else{
                evt.consume();
            }
        }
    }//GEN-LAST:event_x1_addKeyTyped

    private void x3_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_x3_addKeyReleased
        // TODO add your handling code here:
        if(x3_add.getText().length()>0){
            lbl_error_x3_add.setVisible(false);
        }
    }//GEN-LAST:event_x3_addKeyReleased

    private void x3_addKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_x3_addKeyTyped
        // TODO add your handling code here:
        int pto=0;
    int lugares=0;
        char caracter = evt.getKeyChar();
        if(caracter=='.'){
            pto++;
        }
        if( pto>=2){
            pto=2;
        }
        if( lugares>=3){
            lugares--;
        }

        if(caracter == KeyEvent.VK_BACK_SPACE){
            if( pto>=0){
                lugares--;
            }

            if(!x3_add.getText().contains(".")){
                pto=0;
            }
            if( pto==0){
                lugares=0;
            }
        }
        if (x3_add.getText().length() <1 ) {
            char car = evt.getKeyChar();
            if (car!='.' && Character.isDigit(car)) {
                // escribe
            } else {
                evt.consume();  // desecha
            }

        }else{
            if(x3_add.getText().length()<10){
                char num = evt.getKeyChar();
                if (Character.isDigit(num)||num=='.') {
                    if(num=='.'&&pto<2){
                        // escribe
                    }else{
                        if(pto!=0&&num!='.'){
                            lugares++;
                        }
                        if(lugares<3 && num!='.'){
                            // escribe
                        }else{
                            evt.consume();
                        }
                    }
                }else{
                    evt.consume();
                }
            }else{
                evt.consume();
            }
        }
    }//GEN-LAST:event_x3_addKeyTyped

    private void combo_lmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_lmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_lmActionPerformed

    private void check_prefabricados1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check_prefabricados1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_check_prefabricados1MouseClicked

    private void check_prefabricados2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check_prefabricados2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_check_prefabricados2MouseClicked

    private void combo_pmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_pmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_pmActionPerformed

    private void check_prefabricados3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check_prefabricados3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_check_prefabricados3MouseClicked

    private void num_materiales_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_num_materiales_addKeyReleased
        // TODO add your handling code here:
        if(vol_m3_add.getText().length()>0){
        lbl_error_vol_m3_add.setVisible(false);
    }
    }//GEN-LAST:event_num_materiales_addKeyReleased

    private void x1_28dias_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_x1_28dias_addKeyReleased
        // TODO add your handling code here:
        if(x1_28dias_add.getText().length()>0){
            lbl_error_x1_28dias_add.setVisible(false);
        }
    }//GEN-LAST:event_x1_28dias_addKeyReleased

    private void x1_28dias_addKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_x1_28dias_addKeyTyped
        // TODO add your handling code here:
        int pto=0;
    int lugares=0;
        char caracter = evt.getKeyChar();
        if(caracter=='.'){
            pto++;
        }
        if( pto>=2){
            pto=2;
        }
        if( lugares>=3){
            lugares--;
        }

        if(caracter == KeyEvent.VK_BACK_SPACE){
            if( pto>=0){
                lugares--;
            }

            if(!x1_28dias_add.getText().contains(".")){
                pto=0;
            }
            if( pto==0){
                lugares=0;
            }
        }
        if (x1_28dias_add.getText().length() <1 ) {
            char car = evt.getKeyChar();
            if (car!='.' && Character.isDigit(car)) {
                // escribe
            } else {
                evt.consume();  // desecha
            }

        }else{
            if(x1_28dias_add.getText().length()<10){
                char num = evt.getKeyChar();
                if (Character.isDigit(num)||num=='.') {
                    if(num=='.'&&pto<2){
                        // escribe
                    }else{
                        if(pto!=0&&num!='.'){
                            lugares++;
                        }
                        if(lugares<3 && num!='.'){
                            // escribe
                        }else{
                            evt.consume();
                        }
                    }
                }else{
                    evt.consume();
                }
            }else{
                evt.consume();
            }
        }
    }//GEN-LAST:event_x1_28dias_addKeyTyped

    private void x2_28dias_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_x2_28dias_addKeyReleased
        // TODO add your handling code here:
        if(x2_28dias_add.getText().length()>0){
            lbl_error_x2_28dias_add.setVisible(false);
        }
    }//GEN-LAST:event_x2_28dias_addKeyReleased

    private void x2_28dias_addKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_x2_28dias_addKeyTyped
        // TODO add your handling code here:
        int pto=0;
    int lugares=0;
        char caracter = evt.getKeyChar();
        if(caracter=='.'){
            pto++;
        }
        if( pto>=2){
            pto=2;
        }
        if( lugares>=3){
            lugares--;
        }

        if(caracter == KeyEvent.VK_BACK_SPACE){
            if( pto>=0){
                lugares--;
            }

            if(!x2_28dias_add.getText().contains(".")){
                pto=0;
            }
            if( pto==0){
                lugares=0;
            }
        }
        if (x2_28dias_add.getText().length() <1 ) {
            char car = evt.getKeyChar();
            if (car!='.' && Character.isDigit(car)) {
                // escribe
            } else {
                evt.consume();  // desecha
            }

        }else{
            if(x2_28dias_add.getText().length()<10){
                char num = evt.getKeyChar();
                if (Character.isDigit(num)||num=='.') {
                    if(num=='.'&&pto<2){
                        // escribe
                    }else{
                        if(pto!=0&&num!='.'){
                            lugares++;
                        }
                        if(lugares<3 && num!='.'){
                            // escribe
                        }else{
                            evt.consume();
                        }
                    }
                }else{
                    evt.consume();
                }
            }else{
                evt.consume();
            }
        }
    }//GEN-LAST:event_x2_28dias_addKeyTyped

    private void x3_28dias_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_x3_28dias_addKeyReleased
        // TODO add your handling code here:
        if(x3_28dias_add.getText().length()>0){
            lbl_error_x3_28dias_add.setVisible(false);
        }
    }//GEN-LAST:event_x3_28dias_addKeyReleased

    private void x3_28dias_addKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_x3_28dias_addKeyTyped
        // TODO add your handling code here:
        int pto=0;
    int lugares=0;
        char caracter = evt.getKeyChar();
        if(caracter=='.'){
            pto++;
        }
        if( pto>=2){
            pto=2;
        }
        if( lugares>=3){
            lugares--;
        }

        if(caracter == KeyEvent.VK_BACK_SPACE){
            if( pto>=0){
                lugares--;
            }

            if(!x3_28dias_add.getText().contains(".")){
                pto=0;
            }
            if( pto==0){
                lugares=0;
            }
        }
        if (x3_28dias_add.getText().length() <1 ) {
            char car = evt.getKeyChar();
            if (car!='.' && Character.isDigit(car)) {
                // escribe
            } else {
                evt.consume();  // desecha
            }

        }else{
            if(x3_28dias_add.getText().length()<10){
                char num = evt.getKeyChar();
                if (Character.isDigit(num)||num=='.') {
                    if(num=='.'&&pto<2){
                        // escribe
                    }else{
                        if(pto!=0&&num!='.'){
                            lugares++;
                        }
                        if(lugares<3 && num!='.'){
                            // escribe
                        }else{
                            evt.consume();
                        }
                    }
                }else{
                    evt.consume();
                }
            }else{
                evt.consume();
            }
        }
    }//GEN-LAST:event_x3_28dias_addKeyTyped

     private void deshabilitarPegar() {
        InputMap map1 = num_materiales_add.getInputMap(num_materiales_add.WHEN_FOCUSED);
        map1.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");

        InputMap map2 = x3_28dias_add.getInputMap(x3_28dias_add.WHEN_FOCUSED);
        map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
        InputMap map3 = fecha_info_lab_add.getInputMap(fecha_info_lab_add.WHEN_FOCUSED);
        map3.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
        InputMap map4 = vol_m3_add.getInputMap(vol_m3_add.WHEN_FOCUSED);
        map4.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
        InputMap map5 = x1_add.getInputMap(x1_add.WHEN_FOCUSED);
        map5.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
        InputMap map6 = x2_add.getInputMap(x2_add.WHEN_FOCUSED);
        map6.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
        InputMap map7 = x3_add.getInputMap(x3_add.WHEN_FOCUSED);
        map7.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
        InputMap map8 = asent_add.getInputMap(asent_add.WHEN_FOCUSED);
        map8.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
        InputMap map9 = x1_28dias_add.getInputMap(x1_28dias_add.WHEN_FOCUSED);
        map9.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
        InputMap map10 = x2_28dias_add.getInputMap(x2_28dias_add.WHEN_FOCUSED);
        map10.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    }

    private void reset_campos(){
////        cantidad_re_add.setText("");
////        combo_prefabricados_re_add.setSelectedIndex(0);
////        num_materiales_add.setText("");
////        um_re_add.setText("");
////        combo_programas_re_add.setSelectedIndex(0);
////        factura_re_add.setText("");
////        carta_porte_re_add.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static rojeru_san.rsfield.RSTextMaterial asent_add;
    private rojeru_san.RSButtonRiple boton_guardar_recursos_x_programa_add;
    private check_de_android.Switch check_prefabricados1;
    private check_de_android.Switch check_prefabricados2;
    private check_de_android.Switch check_prefabricados3;
    private org.bolivia.combo.SComboBox combo_lm;
    private org.bolivia.combo.SComboBox combo_pm;
    private com.toedter.calendar.JDateChooser fecha_info_lab_add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_error_asent_add;
    private javax.swing.JLabel lbl_error_fecha_info_lab_add;
    private javax.swing.JLabel lbl_error_lm_add;
    private javax.swing.JLabel lbl_error_num_materiales_add;
    private javax.swing.JLabel lbl_error_pm_add;
    private javax.swing.JLabel lbl_error_vol_m3_add;
    private javax.swing.JLabel lbl_error_x1_28dias_add;
    private javax.swing.JLabel lbl_error_x1_add;
    private javax.swing.JLabel lbl_error_x2_28dias_add;
    private javax.swing.JLabel lbl_error_x2_add;
    private javax.swing.JLabel lbl_error_x3_28dias_add;
    private javax.swing.JLabel lbl_error_x3_add;
    public static rojeru_san.rsfield.RSTextMaterial num_materiales_add;
    public static rojeru_san.rsfield.RSTextMaterial vol_m3_add;
    public static rojeru_san.rsfield.RSTextMaterial x1_28dias_add;
    public static rojeru_san.rsfield.RSTextMaterial x1_add;
    public static rojeru_san.rsfield.RSTextMaterial x2_28dias_add;
    public static rojeru_san.rsfield.RSTextMaterial x2_add;
    public static rojeru_san.rsfield.RSTextMaterial x3_28dias_add;
    public static rojeru_san.rsfield.RSTextMaterial x3_add;
    // End of variables declaration//GEN-END:variables
}
