/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles_de_paneles;

import alertas.ErrorAlert;
import alertas.SuccessAlert;
import com.toedter.calendar.JDateChooser;
import esperas.Guardando_general;
import interaccion_bd.consultas_de_gestionar_contrato;
import interaccion_bd.consultas_de_gestionar_recursos_x_programa;
import interaccion_bd.opciones_de_gestionar_contrato;
import interaccion_bd.opciones_de_gestionar_recursos_x_programa;
import java.awt.Event;
import paneles.*;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.lang.reflect.Field;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import static paneles_de_paneles.de_gestionar_contrato_editar.nombre_cliente_contrato_editar;
import static paneles_de_paneles.de_gestionar_contrato_editar.numero_contrato_editar;
import static paneles_de_paneles.de_gestionar_recursos_x_programa_editar.cantidad_re_editar;
import static paneles_de_paneles.de_gestionar_recursos_x_programa_editar.carta_porte_re_editar;
import static paneles_de_paneles.de_gestionar_recursos_x_programa_editar.codigo_re_editar;
import static paneles_de_paneles.de_gestionar_recursos_x_programa_editar.descripcion_re_editar;
import static paneles_de_paneles.de_gestionar_recursos_x_programa_editar.factura_re_editar;
import static paneles_de_paneles.de_gestionar_recursos_x_programa_editar.programa_re_editar;
import static paneles_de_paneles.de_gestionar_recursos_x_programa_editar.um_re_editar;

/**
 *
 * @author RojeruSan
 */
public class de_gestionar_recursos_x_programa_añadir extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public de_gestionar_recursos_x_programa_añadir() {
        initComponents();
        lbl_error_codigo_re_add.setVisible(false);
        lbl_error_descripcion_re_add.setVisible(false);
        lbl_error_um_re_add.setVisible(false);
        lbl_error_cant_re_add.setVisible(false);
        lbl_error_programa_re_add.setVisible(false);
        lbl_error_factura_re_add.setVisible(false);
        lbl_error_carta_porte_add.setVisible(false);
        deshabilitarPegar();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cantidad_re_add = new rojeru_san.rsfield.RSTextMaterial();
        lbl_error_codigo_re_add = new javax.swing.JLabel();
        descripcion_re_add = new rojeru_san.rsfield.RSTextMaterial();
        lbl_error_descripcion_re_add = new javax.swing.JLabel();
        lbl_error_cant_re_add = new javax.swing.JLabel();
        boton_guardar_recursos_x_programa_add = new rojeru_san.RSButtonRiple();
        um_re_add = new rojeru_san.rsfield.RSTextMaterial();
        lbl_error_um_re_add = new javax.swing.JLabel();
        codigo_re_add = new rojeru_san.rsfield.RSTextMaterial();
        programa_re_add = new rojeru_san.rsfield.RSTextMaterial();
        factura_re_add = new rojeru_san.rsfield.RSTextMaterial();
        lbl_error_factura_re_add = new javax.swing.JLabel();
        lbl_error_programa_re_add = new javax.swing.JLabel();
        carta_porte_re_add = new rojeru_san.rsfield.RSTextMaterial();
        lbl_error_carta_porte_add = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_recursos_x_programa/recursos.jpg"))); // NOI18N

        cantidad_re_add.setForeground(new java.awt.Color(0, 0, 0));
        cantidad_re_add.setColorMaterial(new java.awt.Color(99, 70, 250));
        cantidad_re_add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cantidad_re_add.setPlaceholder("Cantidad...");
        cantidad_re_add.setSelectionColor(new java.awt.Color(220, 23, 111));
        cantidad_re_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cantidad_re_addKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidad_re_addKeyTyped(evt);
            }
        });

        lbl_error_codigo_re_add.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_codigo_re_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_codigo_re_add.setText("¡Debe ingresar un código de recurso!");

        descripcion_re_add.setForeground(new java.awt.Color(0, 0, 0));
        descripcion_re_add.setColorMaterial(new java.awt.Color(99, 70, 250));
        descripcion_re_add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        descripcion_re_add.setPlaceholder("Descripción del recurso...");
        descripcion_re_add.setSelectionColor(new java.awt.Color(220, 23, 111));
        descripcion_re_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descripcion_re_addKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                descripcion_re_addKeyTyped(evt);
            }
        });

        lbl_error_descripcion_re_add.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_descripcion_re_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_descripcion_re_add.setText("¡Debe ingresar una descripcion del recurso!");

        lbl_error_cant_re_add.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_cant_re_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_cant_re_add.setText("¡Debe ingresar una cantidad!");

        boton_guardar_recursos_x_programa_add.setBackground(new java.awt.Color(38, 86, 186));
        boton_guardar_recursos_x_programa_add.setText("Guardar Cambios");
        boton_guardar_recursos_x_programa_add.setColorHover(new java.awt.Color(173, 187, 194));
        boton_guardar_recursos_x_programa_add.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_guardar_recursos_x_programa_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardar_recursos_x_programa_addActionPerformed(evt);
            }
        });

        um_re_add.setForeground(new java.awt.Color(0, 0, 0));
        um_re_add.setColorMaterial(new java.awt.Color(99, 70, 250));
        um_re_add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        um_re_add.setPlaceholder("Unidad de medida...");
        um_re_add.setSelectionColor(new java.awt.Color(220, 23, 111));
        um_re_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                um_re_addKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                um_re_addKeyTyped(evt);
            }
        });

        lbl_error_um_re_add.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_um_re_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_um_re_add.setText("¡Debe ingresar una unidad de medida!");

        codigo_re_add.setForeground(new java.awt.Color(0, 0, 0));
        codigo_re_add.setColorMaterial(new java.awt.Color(99, 70, 250));
        codigo_re_add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        codigo_re_add.setPlaceholder("Código del recurso...");
        codigo_re_add.setSelectionColor(new java.awt.Color(220, 23, 111));
        codigo_re_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codigo_re_addKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigo_re_addKeyTyped(evt);
            }
        });

        programa_re_add.setForeground(new java.awt.Color(0, 0, 0));
        programa_re_add.setColorMaterial(new java.awt.Color(99, 70, 250));
        programa_re_add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        programa_re_add.setPlaceholder("Programa al que pertenece...");
        programa_re_add.setSelectionColor(new java.awt.Color(220, 23, 111));
        programa_re_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                programa_re_addKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                programa_re_addKeyTyped(evt);
            }
        });

        factura_re_add.setForeground(new java.awt.Color(0, 0, 0));
        factura_re_add.setColorMaterial(new java.awt.Color(99, 70, 250));
        factura_re_add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        factura_re_add.setPlaceholder("Número de factura...");
        factura_re_add.setSelectionColor(new java.awt.Color(220, 23, 111));
        factura_re_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                factura_re_addKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                factura_re_addKeyTyped(evt);
            }
        });

        lbl_error_factura_re_add.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_factura_re_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_factura_re_add.setText("¡Debe ingresar un número de factura!");

        lbl_error_programa_re_add.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_programa_re_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_programa_re_add.setText("¡Debe ingresar un programa!");

        carta_porte_re_add.setForeground(new java.awt.Color(0, 0, 0));
        carta_porte_re_add.setColorMaterial(new java.awt.Color(99, 70, 250));
        carta_porte_re_add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        carta_porte_re_add.setPlaceholder("Número de carta porte...");
        carta_porte_re_add.setSelectionColor(new java.awt.Color(220, 23, 111));
        carta_porte_re_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                carta_porte_re_addKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                carta_porte_re_addKeyTyped(evt);
            }
        });

        lbl_error_carta_porte_add.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_carta_porte_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_carta_porte_add.setText("¡Debe ingresar un número de carta porte!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(programa_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(factura_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(carta_porte_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(lbl_error_carta_porte_add))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(lbl_error_programa_re_add))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(lbl_error_factura_re_add)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lbl_error_cant_re_add))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(boton_guardar_recursos_x_programa_add, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addComponent(lbl_error_codigo_re_add))
                                .addComponent(descripcion_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(lbl_error_descripcion_re_add))
                                .addComponent(um_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(lbl_error_um_re_add))
                                .addComponent(cantidad_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(codigo_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(codigo_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbl_error_codigo_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(descripcion_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbl_error_descripcion_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(programa_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(um_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_error_um_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_error_programa_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cantidad_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_error_cant_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_error_factura_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(factura_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carta_porte_re_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_guardar_recursos_x_programa_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(lbl_error_carta_porte_add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cantidad_re_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidad_re_addKeyReleased
        // TODO add your handling code here:
        if(cantidad_re_add.getText().length()>0){
            lbl_error_cant_re_add.setVisible(false);
        }
    }//GEN-LAST:event_cantidad_re_addKeyReleased

    private void cantidad_re_addKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidad_re_addKeyTyped
        // TODO add your handling code here:
        char num = evt.getKeyChar();
        if ((num < '0' || num > '9')) {
            evt.consume();

        }
    }//GEN-LAST:event_cantidad_re_addKeyTyped

    private void descripcion_re_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripcion_re_addKeyReleased
        // TODO add your handling code here:
        if(descripcion_re_add.getText().length()>0){
            lbl_error_descripcion_re_add.setVisible(false);
        }
    }//GEN-LAST:event_descripcion_re_addKeyReleased

    private void descripcion_re_addKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripcion_re_addKeyTyped
        // TODO add your handling code here:
        char letras = evt.getKeyChar();
        if ((letras < 'a' || letras > 'z') && (letras < 'A' | letras > 'Z')) {
            if ((letras != 'ñ') && (letras != 'Ñ') && (letras != 'á') && (letras != 'Á') && (letras != 'é') && (letras != 'É') && (letras != 'í')
                && (letras != 'Í') && (letras != 'ó') && (letras != 'Ó') && (letras != 'ú') && (letras != 'Ú') && (letras != ' ')) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_descripcion_re_addKeyTyped

    private void boton_guardar_recursos_x_programa_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardar_recursos_x_programa_addActionPerformed

        String sql="select * from recursos_x_programa where codigo_re='"+codigo_re_add.getText()+"'";
        String mje1="El código de recursos por programa que intenta registrar ya existe";
        String mje2="Por favor introduzca un código distinto de recurso";
        if (codigo_re_add.getText().isEmpty()||descripcion_re_add.getText().isEmpty()||um_re_add.getText().isEmpty()||
                cantidad_re_add.getText().isEmpty()||programa_re_add.getText().isEmpty()||factura_re_add.getText().isEmpty()||
                carta_porte_re_add.getText().isEmpty()) {
            if(codigo_re_add.getText().isEmpty()){
                codigo_re_add.requestFocus();
                lbl_error_codigo_re_add.setVisible(true);
            }else if(descripcion_re_add.getText().isEmpty()){
                descripcion_re_add.requestFocus();
                lbl_error_descripcion_re_add.setVisible(true);
            }else if(um_re_add.getText().isEmpty()){
                um_re_add.requestFocus();
                lbl_error_um_re_add.setVisible(true);
            }else if(cantidad_re_add.getText().isEmpty()){
                cantidad_re_add.requestFocus();
                lbl_error_cant_re_add.setVisible(true);
            }else if(programa_re_add.getText().isEmpty()){
                programa_re_add.requestFocus();
                lbl_error_programa_re_add.setVisible(true);
            }else if(factura_re_add.getText().isEmpty()){
                factura_re_add.requestFocus();
                lbl_error_factura_re_add.setVisible(true);
            }else if(carta_porte_re_add.getText().isEmpty()){
                carta_porte_re_add.requestFocus();
                lbl_error_carta_porte_add.setVisible(true);
            }
        } else {
                if (interaccion_bd.opciones_de_gestionar_contrato.existe(codigo_re_add.getText(), sql)) {
                    opciones_de_gestionar_contrato.lanza_error_variable_sin_ex("",mje1,mje2);
                    cantidad_re_add.requestFocus();
                }else{
                    Guardando_general l = new Guardando_general(new JFrame(), true);
                    consultas_de_gestionar_recursos_x_programa uc=new consultas_de_gestionar_recursos_x_programa();
                    l.setLocationRelativeTo(paneles_de_paneles.de_gestionar_recursos_x_programa_añadir.this);
                    l.setVisible(true);
                    paneles_de_paneles.de_gestionar_recursos_x_programa_añadir.this.setEnabled(false);
                    uc.setCodigo(codigo_re_add.getText());
                uc.setDescripcion(descripcion_re_add.getText());
                uc.setUm(um_re_add.getText());
                uc.setCant(cantidad_re_add.getText());
                uc.setPrograma_pertenece(programa_re_add.getText());
                uc.setFactura(factura_re_add.getText());
                uc.setCarta_porte(carta_porte_re_add.getText());
                    int control= opciones_de_gestionar_recursos_x_programa.registrar(uc);
                    paneles_de_paneles.de_gestionar_recursos_x_programa_añadir.this.setEnabled(true);
                    l.setVisible(false);
                    if(control==1){
                        reset_campos();
                        opciones_de_gestionar_recursos_x_programa.setListar("");
                        SuccessAlert e = new SuccessAlert(new JFrame(), true);
                        e.msj1.setText("¡Los datos del recurso fueron");
                        e.msj2.setText("guardados exitosamente!.");
                        e.msj3.setText("");
                        e.setVisible(true);
                    }
                }
            
        }
    }//GEN-LAST:event_boton_guardar_recursos_x_programa_addActionPerformed

    private void um_re_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_um_re_addKeyReleased
        // TODO add your handling code here:
        if(um_re_add.getText().length()>0){
        lbl_error_um_re_add.setVisible(false);
        }
    }//GEN-LAST:event_um_re_addKeyReleased

    private void um_re_addKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_um_re_addKeyTyped
        // TODO add your handling code here:
        char letras = evt.getKeyChar();
        if ((letras < 'a' || letras > 'z') && (letras < 'A' | letras > 'Z')) {
            if ((letras != 'ñ') && (letras != 'Ñ') && (letras != 'á') && (letras != 'Á') && (letras != 'é') && (letras != 'É') && (letras != 'í')
                    && (letras != 'Í') && (letras != 'ó') && (letras != 'Ó') && (letras != 'ú') && (letras != 'Ú') && (letras != ' ')) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_um_re_addKeyTyped

    private void codigo_re_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigo_re_addKeyReleased
        // TODO add your handling code here:
        if(codigo_re_add.getText().length()>0){
            lbl_error_codigo_re_add.setVisible(false);
        }
    }//GEN-LAST:event_codigo_re_addKeyReleased

    private void codigo_re_addKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigo_re_addKeyTyped
        // TODO add your handling code here:
        char num = evt.getKeyChar();
        if ((num < '0' || num > '9')) {
            evt.consume();
            
        }
    }//GEN-LAST:event_codigo_re_addKeyTyped

    private void programa_re_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_programa_re_addKeyReleased
        // TODO add your handling code here:
        if(programa_re_add.getText().length()>0){
        lbl_error_programa_re_add.setVisible(false);
        }
    }//GEN-LAST:event_programa_re_addKeyReleased

    private void programa_re_addKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_programa_re_addKeyTyped
        // TODO add your handling code here:
        char letras = evt.getKeyChar();
        if ((letras < 'a' || letras > 'z') && (letras < 'A' | letras > 'Z')) {
            if ((letras != 'ñ') && (letras != 'Ñ') && (letras != 'á') && (letras != 'Á') && (letras != 'é') && (letras != 'É') && (letras != 'í')
                    && (letras != 'Í') && (letras != 'ó') && (letras != 'Ó') && (letras != 'ú') && (letras != 'Ú') && (letras != ' ')) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_programa_re_addKeyTyped

    private void factura_re_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_factura_re_addKeyReleased
        // TODO add your handling code here:
        if(factura_re_add.getText().length()>0){
            lbl_error_factura_re_add.setVisible(false);
        }
    }//GEN-LAST:event_factura_re_addKeyReleased

    private void factura_re_addKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_factura_re_addKeyTyped
        // TODO add your handling code here:
        char num = evt.getKeyChar();
        if ((num < '0' || num > '9')) {
            evt.consume();
            
        }
    }//GEN-LAST:event_factura_re_addKeyTyped

    private void carta_porte_re_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carta_porte_re_addKeyReleased
        // TODO add your handling code here:
        if(carta_porte_re_add.getText().length()>0){
            lbl_error_carta_porte_add.setVisible(false);
        }
    }//GEN-LAST:event_carta_porte_re_addKeyReleased

    private void carta_porte_re_addKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carta_porte_re_addKeyTyped
        // TODO add your handling code here:
        char num = evt.getKeyChar();
        if ((num < '0' || num > '9')) {
            evt.consume();
            
        }
    }//GEN-LAST:event_carta_porte_re_addKeyTyped

     private void deshabilitarPegar() {
        InputMap map1 = codigo_re_add.getInputMap(codigo_re_add.WHEN_FOCUSED);
        map1.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");

        InputMap map2 = descripcion_re_add.getInputMap(descripcion_re_add.WHEN_FOCUSED);
        map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
        InputMap map3 = um_re_add.getInputMap(um_re_add.WHEN_FOCUSED);
        map3.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
        InputMap map4 = cantidad_re_add.getInputMap(cantidad_re_add.WHEN_FOCUSED);
        map4.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
        InputMap map5 = programa_re_add.getInputMap(programa_re_add.WHEN_FOCUSED);
        map5.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
        InputMap map6 = factura_re_add.getInputMap(factura_re_add.WHEN_FOCUSED);
        map6.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
        InputMap map7 = carta_porte_re_add.getInputMap(carta_porte_re_add.WHEN_FOCUSED);
        map7.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    }

    private void reset_campos(){
        cantidad_re_add.setText("");
        descripcion_re_add.setText("");
        codigo_re_add.setText("");
        um_re_add.setText("");
        programa_re_add.setText("");
        factura_re_add.setText("");
        carta_porte_re_add.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple boton_guardar_recursos_x_programa_add;
    public static rojeru_san.rsfield.RSTextMaterial cantidad_re_add;
    public static rojeru_san.rsfield.RSTextMaterial carta_porte_re_add;
    public static rojeru_san.rsfield.RSTextMaterial codigo_re_add;
    public static rojeru_san.rsfield.RSTextMaterial descripcion_re_add;
    public static rojeru_san.rsfield.RSTextMaterial factura_re_add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_error_cant_re_add;
    private javax.swing.JLabel lbl_error_carta_porte_add;
    private javax.swing.JLabel lbl_error_codigo_re_add;
    private javax.swing.JLabel lbl_error_descripcion_re_add;
    private javax.swing.JLabel lbl_error_factura_re_add;
    private javax.swing.JLabel lbl_error_programa_re_add;
    private javax.swing.JLabel lbl_error_um_re_add;
    public static rojeru_san.rsfield.RSTextMaterial programa_re_add;
    public static rojeru_san.rsfield.RSTextMaterial um_re_add;
    // End of variables declaration//GEN-END:variables
}
