/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles_de_paneles;

import DAO.PdfDAO;
import DAO.PdfDAO_prep_tecnica;
import Tabla.Tabla_PdfVO;
import Tabla.Tabla_PdfVO_prep_tecnica;
import VO.PdfVO;
import VO.PdfVO_prep_tecnica;
import alertas.ErrorAlert;
import alertas.SuccessAlert;
import alertas.WarningAlert;
import esperas.Guardando_general;
import interaccion_bd.opciones_de_gestionar_contrato;
import java.awt.Event;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.InputMap;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author RojeruSan
 */
public class de_gestionar_proyecto_añadir extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public de_gestionar_proyecto_añadir() {
        initComponents();
        lbl_error_nombre_proy.setVisible(false);
        lbl_error_pdf_proy.setVisible(false);
        deshabilitarPegar();
    }

     String  ruta_archivo="";
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre_proy = new rojeru_san.rsfield.RSTextMaterial();
        lbl_error_nombre_proy = new javax.swing.JLabel();
        boton_guardar_proy = new rojeru_san.RSButtonRiple();
        lb_foto = new javax.swing.JLabel();
        boton_busca_proy = new rojeru_san.RSButtonRiple();
        lbl_error_pdf_proy = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        nombre_proy.setForeground(new java.awt.Color(0, 0, 0));
        nombre_proy.setColorMaterial(new java.awt.Color(99, 70, 250));
        nombre_proy.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nombre_proy.setPlaceholder("Nombre del plano...");
        nombre_proy.setSelectionColor(new java.awt.Color(220, 23, 111));
        nombre_proy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombre_proyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombre_proyKeyTyped(evt);
            }
        });

        lbl_error_nombre_proy.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_nombre_proy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_nombre_proy.setText("¡Debe ingresar un nombre de plano!");

        boton_guardar_proy.setBackground(new java.awt.Color(38, 86, 186));
        boton_guardar_proy.setText("Guardar Plano");
        boton_guardar_proy.setColorHover(new java.awt.Color(173, 187, 194));
        boton_guardar_proy.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_guardar_proy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardar_proyActionPerformed(evt);
            }
        });

        lb_foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_planos/foto_plano.png"))); // NOI18N

        boton_busca_proy.setBackground(new java.awt.Color(38, 86, 186));
        boton_busca_proy.setText("Buscar Plano");
        boton_busca_proy.setColorHover(new java.awt.Color(173, 187, 194));
        boton_busca_proy.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton_busca_proy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_busca_proyActionPerformed(evt);
            }
        });

        lbl_error_pdf_proy.setForeground(new java.awt.Color(243, 66, 53));
        lbl_error_pdf_proy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_error/label-error-backup.png"))); // NOI18N
        lbl_error_pdf_proy.setText("¡Debe buscar un plano!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lbl_error_nombre_proy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nombre_proy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(boton_guardar_proy, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(boton_busca_proy, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(lbl_error_pdf_proy)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(nombre_proy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbl_error_nombre_proy, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(boton_guardar_proy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(boton_busca_proy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbl_error_pdf_proy, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombre_proyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_proyKeyReleased
        // TODO add your handling code here:
        if(nombre_proy.getText().length()>0){
            lbl_error_nombre_proy.setVisible(false);
        }
    }//GEN-LAST:event_nombre_proyKeyReleased

    private void nombre_proyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_proyKeyTyped
        // TODO add your handling code here:
        char letras = evt.getKeyChar();
        if ((letras < 'a' || letras > 'z') && (letras < 'A' | letras > 'Z')) {
            if ((letras != 'ñ') && (letras != 'Ñ') && (letras != 'á') && (letras != 'Á') && (letras != 'é') && (letras != 'É') && (letras != 'í')
                && (letras != 'Í') && (letras != 'ó') && (letras != 'Ó') && (letras != 'ú') && (letras != 'Ú') && (letras != ' ')) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_nombre_proyKeyTyped

    Tabla_PdfVO_prep_tecnica tpdf = new Tabla_PdfVO_prep_tecnica();
    private void boton_guardar_proyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardar_proyActionPerformed
       String sql="select * from prep_tecnica where nombre_prep_tecnica='"+nombre_proy.getText()+"'";
       String mje1="Ya existe una preparación técnica con ese nombre("+nombre_proy.getText()+")";
       String mje2="¿Desea guardarlo de todas farmas?";
       String mje3="La base de datos contendrá más de una preparación técnica con el mismo nombre";
        if (nombre_proy.getText().isEmpty()||boton_busca_proy.getText().equals("Buscar Plano")) {
               if(nombre_proy.getText().isEmpty()){
                lbl_error_nombre_proy.setVisible(true);
               }else if(boton_busca_proy.getText().equals("Buscar Plano")){
                lbl_error_pdf_proy.setVisible(true);
               }
        } else {
            if (interaccion_bd.opciones_de_gestionar_contrato.existe(nombre_proy.getText(), sql)) {
                WarningAlert a=new WarningAlert(new JFrame(), true);
                            a.msj1.setText(mje1);
                            a.msj2.setText(mje2);
                            a.msj3.setText(mje3);
                            a.setVisible(true);
                            if(a.hecho==false){
                            nombre_proy.requestFocus();
                            }else{
                                Runnable runnable1 = new Runnable() {
                public void run() {
                    Guardando_general l = new Guardando_general(new JFrame(), true);
                    l.setLocationRelativeTo(paneles_de_paneles.de_gestionar_proyecto_añadir.this);
                    l.setVisible(true);
                    try{
                    paneles_de_paneles.de_gestionar_proyecto_añadir.this.setEnabled(false);
                    accion_guardar();
                    paneles_de_paneles.de_gestionar_proyecto_añadir.this.setEnabled(true);
                    l.setVisible(false);
                        
                    }catch(Exception e){
                        Logger.getLogger(opciones_de_gestionar_contrato.class.getName()).log(Level.SEVERE, null, e);
                        opciones_de_gestionar_contrato.lanza_error(e);
                    }
                }
            };
            Thread t1 = new Thread(runnable1);
            t1.start();
                            }
                        }else{
            Runnable runnable1 = new Runnable() {
                public void run() {
                    Guardando_general l = new Guardando_general(new JFrame(), true);
                    l.setLocationRelativeTo(paneles_de_paneles.de_gestionar_proyecto_añadir.this);
                    l.setVisible(true);
                    try{
                    paneles_de_paneles.de_gestionar_proyecto_añadir.this.setEnabled(false);
                    accion_guardar();
                    paneles_de_paneles.de_gestionar_proyecto_añadir.this.setEnabled(true);
                    l.setVisible(false);
                        
                    }catch(Exception e){
                        Logger.getLogger(opciones_de_gestionar_contrato.class.getName()).log(Level.SEVERE, null, e);
                        opciones_de_gestionar_contrato.lanza_error(e);
                    }
                }
            };
            Thread t1 = new Thread(runnable1);
            t1.start();
        }
    }
    }//GEN-LAST:event_boton_guardar_proyActionPerformed

    public void accion_guardar(){
        try{
        String nombre = nombre_proy.getText();
        File ruta = new File(ruta_archivo);
        if (nombre.trim().length() != 0 && ruta_archivo.trim().length() != 0) {
            guardar_pdf(nombre, ruta);
         //   tpdf.visualizar_PdfVO(tabla);
            ruta_archivo = "";
            reset_campos();
            SuccessAlert e = new SuccessAlert(new JFrame(), true);
            e.msj1.setText("¡Los datos de la preparación técnica fueron");
            e.msj2.setText("guardados exitosamente!.");
            e.msj3.setText("");
            e.setVisible(true);
        } 
        }catch(Exception ex){
            opciones_de_gestionar_contrato.lanza_error(ex);
        }
    }
    
    public void guardar_pdf( String nombre, File ruta) {
        PdfDAO_prep_tecnica pa = new PdfDAO_prep_tecnica();
        PdfVO_prep_tecnica po = new PdfVO_prep_tecnica();
        po.setNombrepdf(nombre);
        try {
            byte[] pdf = new byte[(int) ruta.length()];
            InputStream input = new FileInputStream(ruta);
            input.read(pdf);
            po.setArchivopdf(pdf);
        } catch (IOException ex) {
            po.setArchivopdf(null);
        }
        pa.Agregar_PdfVO(po);
    }
    
    private void boton_busca_proyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_busca_proyActionPerformed
        // TODO add your handling code here:
        try{
         JFileChooser j = new JFileChooser();
        FileNameExtensionFilter fi = new FileNameExtensionFilter("pdf", "pdf");
        j.setFileFilter(fi);
        int se = j.showOpenDialog(this);
        if (se == 0) {
            this.boton_busca_proy.setText("" + j.getSelectedFile().getName());
          ruta_archivo = j.getSelectedFile().getAbsolutePath();
          
          lb_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_planos/pdf2.png"))); 
          lbl_error_pdf_proy.setVisible(false);
        }  
        }catch(Exception ex){
            opciones_de_gestionar_contrato.lanza_error(ex);
        }
    }//GEN-LAST:event_boton_busca_proyActionPerformed

     private void deshabilitarPegar() {
        InputMap map2 = nombre_proy.getInputMap(nombre_proy.WHEN_FOCUSED);
        map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    }
               
    private void reset_campos(){
        nombre_proy.setText("");
        boton_busca_proy.setText("Buscar Plano");
        lb_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_planos/foto_plano.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple boton_busca_proy;
    private rojeru_san.RSButtonRiple boton_guardar_proy;
    private javax.swing.JLabel lb_foto;
    private javax.swing.JLabel lbl_error_nombre_proy;
    private javax.swing.JLabel lbl_error_pdf_proy;
    public static rojeru_san.rsfield.RSTextMaterial nombre_proy;
    // End of variables declaration//GEN-END:variables
}
