/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import interaccion_bd.opciones_de_gestionar_contrato;
import interaccion_bd.opciones_de_gestionar_usuarios;
import java.awt.Color;

/**
 *
 * @author RojeruSan
 */
public class pnl_Gestionar_prod_programa extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public pnl_Gestionar_prod_programa() {
        initComponents();
      //  new CambiaPanel(panel_contenedor, new paneles.pnlHome());
        this.listar_contrato.setSelected(true);
        new CambiaPanel(panel_contenedor, new paneles_de_paneles.de_gestionar_prod_programa_listar());
        color_performed(listar_contrato, add_contrato);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        listar_contrato1 = new rsbuttom.RSButtonMetro();
        add_contrato1 = new rsbuttom.RSButtonMetro();
        panel_contenedor1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        listar_contrato = new rsbuttom.RSButtonMetro();
        add_contrato = new rsbuttom.RSButtonMetro();
        panel_contenedor = new javax.swing.JPanel();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/splash_logo.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(128, 128, 131));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Gestionar Contrato");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/splash_logo.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(128, 128, 131));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Gestionar Contrato");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(128, 128, 131));
        jLabel10.setText("Gestionar Producción por Programa");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 6, 0, 6);
        jPanel1.add(jLabel10, gridBagConstraints);

        listar_contrato1.setBackground(new java.awt.Color(239, 238, 244));
        listar_contrato1.setForeground(new java.awt.Color(128, 128, 131));
        listar_contrato1.setText("Listar");
        listar_contrato1.setColorHover(new java.awt.Color(204, 204, 204));
        listar_contrato1.setColorNormal(new java.awt.Color(239, 238, 244));
        listar_contrato1.setColorPressed(new java.awt.Color(204, 204, 204));
        listar_contrato1.setColorTextHover(new java.awt.Color(128, 128, 131));
        listar_contrato1.setColorTextNormal(new java.awt.Color(128, 128, 131));
        listar_contrato1.setColorTextPressed(new java.awt.Color(128, 128, 131));
        listar_contrato1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listar_contrato1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        listar_contrato1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        listar_contrato1.setIconTextGap(25);
        listar_contrato1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listar_contrato1MousePressed(evt);
            }
        });
        listar_contrato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listar_contrato1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel1.add(listar_contrato1, gridBagConstraints);

        add_contrato1.setBackground(new java.awt.Color(239, 238, 244));
        add_contrato1.setForeground(new java.awt.Color(128, 128, 131));
        add_contrato1.setText("Añadir");
        add_contrato1.setColorHover(new java.awt.Color(204, 204, 204));
        add_contrato1.setColorNormal(new java.awt.Color(239, 238, 244));
        add_contrato1.setColorPressed(new java.awt.Color(204, 204, 204));
        add_contrato1.setColorTextHover(new java.awt.Color(128, 128, 131));
        add_contrato1.setColorTextNormal(new java.awt.Color(128, 128, 131));
        add_contrato1.setColorTextPressed(new java.awt.Color(128, 128, 131));
        add_contrato1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add_contrato1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add_contrato1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add_contrato1.setIconTextGap(25);
        add_contrato1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                add_contrato1MousePressed(evt);
            }
        });
        add_contrato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_contrato1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel1.add(add_contrato1, gridBagConstraints);

        panel_contenedor1.setBackground(new java.awt.Color(255, 255, 255));
        panel_contenedor1.setLayout(new javax.swing.BoxLayout(panel_contenedor1, javax.swing.BoxLayout.LINE_AXIS));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 859;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        jPanel1.add(panel_contenedor1, gridBagConstraints);

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(128, 128, 131));
        jLabel9.setText("Gestionar Producción por Programa");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        listar_contrato.setBackground(new java.awt.Color(239, 238, 244));
        listar_contrato.setForeground(new java.awt.Color(128, 128, 131));
        listar_contrato.setText("Listar");
        listar_contrato.setColorHover(new java.awt.Color(204, 204, 204));
        listar_contrato.setColorNormal(new java.awt.Color(239, 238, 244));
        listar_contrato.setColorPressed(new java.awt.Color(204, 204, 204));
        listar_contrato.setColorTextHover(new java.awt.Color(128, 128, 131));
        listar_contrato.setColorTextNormal(new java.awt.Color(128, 128, 131));
        listar_contrato.setColorTextPressed(new java.awt.Color(128, 128, 131));
        listar_contrato.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listar_contrato.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        listar_contrato.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        listar_contrato.setIconTextGap(25);
        listar_contrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listar_contratoMousePressed(evt);
            }
        });
        listar_contrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listar_contratoActionPerformed(evt);
            }
        });

        add_contrato.setBackground(new java.awt.Color(239, 238, 244));
        add_contrato.setForeground(new java.awt.Color(128, 128, 131));
        add_contrato.setText("Añadir");
        add_contrato.setColorHover(new java.awt.Color(204, 204, 204));
        add_contrato.setColorNormal(new java.awt.Color(239, 238, 244));
        add_contrato.setColorPressed(new java.awt.Color(204, 204, 204));
        add_contrato.setColorTextHover(new java.awt.Color(128, 128, 131));
        add_contrato.setColorTextNormal(new java.awt.Color(128, 128, 131));
        add_contrato.setColorTextPressed(new java.awt.Color(128, 128, 131));
        add_contrato.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add_contrato.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add_contrato.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add_contrato.setIconTextGap(25);
        add_contrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                add_contratoMousePressed(evt);
            }
        });
        add_contrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_contratoActionPerformed(evt);
            }
        });

        panel_contenedor.setBackground(new java.awt.Color(255, 255, 255));
        panel_contenedor.setLayout(new javax.swing.BoxLayout(panel_contenedor, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listar_contrato, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add_contrato, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(755, 755, 755))
                    .addComponent(panel_contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_contrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listar_contrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void add_contratoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_contratoMousePressed
        // TODO add your handling code here:
        pressed(add_contrato,listar_contrato);
    }//GEN-LAST:event_add_contratoMousePressed

    private void add_contratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_contratoActionPerformed
        // TODO add your handling code here:
        String sql_permiso="SELECT * FROM `permisos` WHERE `usuario_permisos`='"+principal.Principal.user.getText().trim()+"' and `apartado_permisos`='producción por programa'"
                + "and add_permisos='1' ";
        String mj1="Usted no cuenta con los permisos requeridos para accedeer a este apartado.";
        String mj2="Si considera que estamos en un error contacte con el administrador del ";
        String mj3="sistema para que le otorgue los permisos pertinentes";
        if(opciones_de_gestionar_usuarios.existe(sql_permiso)){
        new CambiaPanel(panel_contenedor, new paneles_de_paneles.de_gestionar_prod_programa_añadir());
        color_performed(add_contrato,listar_contrato);
        }else{
            opciones_de_gestionar_contrato.lanza_error_variable_sin_ex(mj1, mj2, mj3);
        }
    }//GEN-LAST:event_add_contratoActionPerformed

    public static void color_performed(rsbuttom.RSButtonMetro principal, rsbuttom.RSButtonMetro uno){
        if(principal.isSelected()){
            principal.setColorNormal(new Color(204,204,204));
            principal.setColorHover(new Color(204,204,204));
            principal.setColorPressed(new Color(204,204,204));
            
            uno.setColorNormal(new Color(239,238,244));
            uno.setColorHover(new Color(204,204,204));
            uno.setColorPressed(new Color(204,204,204));
        }else{
            principal.setColorNormal(new Color(239,238,244));
            principal.setColorHover(new Color(204,204,204));
            principal.setColorPressed(new Color(204,204,204));
        }
    }
    
    public static  void pressed(rsbuttom.RSButtonMetro principal, rsbuttom.RSButtonMetro uno){
        principal.setSelected(true);
        uno.setSelected(false);
    }
    
    private void listar_contratoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listar_contratoMousePressed
        // TODO add your handling code here:
        pressed(listar_contrato,add_contrato);
    }//GEN-LAST:event_listar_contratoMousePressed

    private void listar_contratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listar_contratoActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(panel_contenedor, new paneles_de_paneles.de_gestionar_prod_programa_listar());
        color_performed(listar_contrato,add_contrato);
    }//GEN-LAST:event_listar_contratoActionPerformed

    private void listar_contrato1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listar_contrato1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_listar_contrato1MousePressed

    private void listar_contrato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listar_contrato1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listar_contrato1ActionPerformed

    private void add_contrato1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_contrato1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_contrato1MousePressed

    private void add_contrato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_contrato1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_contrato1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro add_contrato;
    private rsbuttom.RSButtonMetro add_contrato1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private rsbuttom.RSButtonMetro listar_contrato;
    private rsbuttom.RSButtonMetro listar_contrato1;
    private javax.swing.JPanel panel_contenedor;
    private javax.swing.JPanel panel_contenedor1;
    // End of variables declaration//GEN-END:variables
}
