/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import interaccion_bd.opciones_de_gestionar_contrato;
import interaccion_bd.opciones_de_gestionar_usuarios;

/**
 *
 * @author RojeruSan
 */
public class pnl_gestionar_recursos_x_programa extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public pnl_gestionar_recursos_x_programa() {
        initComponents();
        this.listar_recursos_x_programa.setSelected(true);
         new CambiaPanel(panel_contenedor, new paneles_de_paneles.de_gestionar_recursos_x_programa_listar());
         pnl_Gestionar_contrato.color_performed(listar_recursos_x_programa,add_recursos_x_programa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        listar_recursos_x_programa = new rsbuttom.RSButtonMetro();
        add_recursos_x_programa = new rsbuttom.RSButtonMetro();
        panel_contenedor = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Gestionar Recursos por Programa");

        listar_recursos_x_programa.setBackground(new java.awt.Color(239, 238, 244));
        listar_recursos_x_programa.setForeground(new java.awt.Color(128, 128, 131));
        listar_recursos_x_programa.setText("Listar");
        listar_recursos_x_programa.setColorHover(new java.awt.Color(204, 204, 204));
        listar_recursos_x_programa.setColorNormal(new java.awt.Color(239, 238, 244));
        listar_recursos_x_programa.setColorPressed(new java.awt.Color(204, 204, 204));
        listar_recursos_x_programa.setColorTextHover(new java.awt.Color(128, 128, 131));
        listar_recursos_x_programa.setColorTextNormal(new java.awt.Color(128, 128, 131));
        listar_recursos_x_programa.setColorTextPressed(new java.awt.Color(128, 128, 131));
        listar_recursos_x_programa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listar_recursos_x_programa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        listar_recursos_x_programa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        listar_recursos_x_programa.setIconTextGap(25);
        listar_recursos_x_programa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listar_recursos_x_programaMousePressed(evt);
            }
        });
        listar_recursos_x_programa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listar_recursos_x_programaActionPerformed(evt);
            }
        });

        add_recursos_x_programa.setBackground(new java.awt.Color(239, 238, 244));
        add_recursos_x_programa.setForeground(new java.awt.Color(128, 128, 131));
        add_recursos_x_programa.setText("Añadir");
        add_recursos_x_programa.setColorHover(new java.awt.Color(204, 204, 204));
        add_recursos_x_programa.setColorNormal(new java.awt.Color(239, 238, 244));
        add_recursos_x_programa.setColorPressed(new java.awt.Color(204, 204, 204));
        add_recursos_x_programa.setColorTextHover(new java.awt.Color(128, 128, 131));
        add_recursos_x_programa.setColorTextNormal(new java.awt.Color(128, 128, 131));
        add_recursos_x_programa.setColorTextPressed(new java.awt.Color(128, 128, 131));
        add_recursos_x_programa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add_recursos_x_programa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add_recursos_x_programa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add_recursos_x_programa.setIconTextGap(25);
        add_recursos_x_programa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                add_recursos_x_programaMousePressed(evt);
            }
        });
        add_recursos_x_programa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_recursos_x_programaActionPerformed(evt);
            }
        });

        panel_contenedor.setBackground(new java.awt.Color(255, 255, 255));
        panel_contenedor.setLayout(new javax.swing.BoxLayout(panel_contenedor, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listar_recursos_x_programa, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add_recursos_x_programa, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_recursos_x_programa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listar_recursos_x_programa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(panel_contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listar_recursos_x_programaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listar_recursos_x_programaMousePressed
        // TODO add your handling code here:
        pnl_Gestionar_contrato.pressed(listar_recursos_x_programa,add_recursos_x_programa);
    }//GEN-LAST:event_listar_recursos_x_programaMousePressed

    private void listar_recursos_x_programaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listar_recursos_x_programaActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(panel_contenedor, new paneles_de_paneles.de_gestionar_recursos_x_programa_listar());
         pnl_Gestionar_contrato.color_performed(listar_recursos_x_programa,add_recursos_x_programa);
    }//GEN-LAST:event_listar_recursos_x_programaActionPerformed

    private void add_recursos_x_programaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_recursos_x_programaMousePressed
        // TODO add your handling code here:
         pnl_Gestionar_contrato.pressed(add_recursos_x_programa,listar_recursos_x_programa);
    }//GEN-LAST:event_add_recursos_x_programaMousePressed

    private void add_recursos_x_programaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_recursos_x_programaActionPerformed
        // TODO add your handling code here:
       String sql_permiso="SELECT * FROM `permisos` WHERE `usuario_permisos`='"+principal.Principal.user.getText().trim()+"' and `apartado_permisos`='RECURSOS POR PROGRAMA'"
                + "and add_permisos='1' ";
        String mj1="Usted no cuenta con los permisos requeridos para accedeer a este apartado.";
        String mj2="Si considera que estamos en un error contacte con el administrador del ";
        String mj3="sistema para que le otorgue los permisos pertinentes";
        if(opciones_de_gestionar_usuarios.existe(sql_permiso)){
        new CambiaPanel(panel_contenedor, new paneles_de_paneles.de_gestionar_recursos_x_programa_añadir());
         pnl_Gestionar_contrato.color_performed(add_recursos_x_programa,listar_recursos_x_programa);
         }else{
            opciones_de_gestionar_contrato.lanza_error_variable_sin_ex(mj1, mj2, mj3);
        }
    }//GEN-LAST:event_add_recursos_x_programaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro add_recursos_x_programa;
    private javax.swing.JLabel jLabel7;
    private rsbuttom.RSButtonMetro listar_recursos_x_programa;
    private javax.swing.JPanel panel_contenedor;
    // End of variables declaration//GEN-END:variables
}
